// ==UserScript==
/* globals      ß */
// @name        Label dictionary
// @version     2019.4.26.0
// @namespace   https: //github.com/brianfreud
// @downloadURL https: //raw.githubusercontent.com/brianfreud/Userscripts/edit/master/dict_labels.js
// @updateURL   https: //raw.githubusercontent.com/brianfreud/Userscripts/edit/master/dict_labels.js
// ==/UserScript==

// handy master prefix list: https: //pmamusic.com/all-prefixes/

ß.labelDB = [
{name: '101 dark orchid', country: '', mbid: '', prefix: '101DOM'},
{name: '101 music', country: '', mbid: 'b9e5d8b4-44fa-4f79-b72d-435e52036a65', prefix: '101M'},
{name: '101 production music', country: 'AU', mbid: '', prefix: '101PM'},
{name: '1 revolution music', country: '', mbid: '', prefix: '1RM'},
{name: '2nd foundation music', country: '', mbid: '', prefix: '2FM'},
{name: '42 records', country: '', mbid: '', prefix: '42'},
{name: '4 elements music', country: 'US', mbid: '', prefix: '4EM'},
{name: '9 lives music', country: '', mbid: '', prefix: 'NLM'},
{name: 'abaco music', country: '', mbid: 'd595bbf8-1be3-41d1-83f8-c871b39082d2', prefix: 'AB'},
{name: 'abaco music', country: '', mbid: 'd595bbf8-1be3-41d1-83f8-c871b39082d2', prefix: 'AB-CD'},
{name: 'absolute music', country: 'GB', mbid: 'd595bbf8-1be3-41d1-83f8-c871b39082d2', prefix: 'ABS'},
{name: 'adrenalin', country: 'AU', mbid: '', prefix: 'AD'},
{name: 'adrenalin vocals', country: 'AU', mbid: 'ba3037fb-65dc-42ad-9eb3-71e0014205f5', prefix: 'ADV'},
{name: 'afro dizzy', country: '', mbid: 'd8889e78-f436-45f6-b8a0-8dce30c1e2cc', prefix: 'ADZ'},
{name: 'afro musique', country: '', mbid: '', prefix: 'AFRO'},
{name: 'altitude music', country: '', mbid: '', prefix: 'ALT'},
{name: 'altitude underscore', country: '', mbid: '', prefix: 'AU'},
{name: 'altitude x faber', country: '', mbid: '', prefix: 'AXF'},
{name: 'amped', country: '', mbid: '', prefix: 'AMPD'},
{name: 'amplitude', country: 'AU', mbid: 'ac0193ee-ff6d-4e93-b62b-c46b9a685605', prefix: 'AMPT'},
{name: 'amusicom', country: 'US', mbid: '102f1347-8c9e-42e3-a7f8-10ed264cfdb6', prefix: 'AM'},
{name: 'analog champion', country: '', mbid: '', prefix: 'ACPM'},
{name: 'anonymous recordings', country: '', mbid: '', prefix: 'AR'},
{name: 'arcadia cinematic', country: 'GB', mbid: '110ad289-2454-410f-9bf4-c4b55751910d', prefix: 'AC'},
{name: 'arcadia classical media music', country: 'GB', mbid: '', prefix: 'CMC'},
{name: 'arcadia cosmos', country: 'GB', mbid: 'adc009c8-5409-4f74-8abe-cba5c381669a', prefix: '375'},
{name: 'arcadia cosmos special select', country: 'GB', mbid: '', prefix: 'COS'},
{name: 'arcadia deluxe', country: 'GB', mbid: 'b577f5a1-fe0f-431f-952d-923e1f56503f', prefix: 'DL'},
{name: 'arcadia drones', country: 'GB', mbid: '', prefix: 'ARD'},
{name: 'arcadia envogue', country: 'GB', mbid: '', prefix: 'ENV'},
{name: 'arcadia esovision', country: 'GB', mbid: '2a92658e-edbb-454a-bb9d-8b42cea9985b', prefix: 'EV'},
{name: 'arcadia galaxy music lexicon', country: 'GB', mbid: '', prefix: 'GML'},
{name: 'arcadia global authentic music', country: 'GB', mbid: '', prefix: 'GAM'},
{name: 'arcadia hollywood', country: 'GB', mbid: '016ec2ce-0da8-485e-b77a-14ee7715a1e0', prefix: 'HSMS'},
{name: 'arcadia jazz line', country: 'GB', mbid: '57a22081-a4e6-4153-98e6-8c9db393fa0c', prefix: 'JL'},
{name: 'arcadia jingle bank', country: 'GB', mbid: '', prefix: 'AJB'},
{name: 'arcadia less-is-more', country: 'GB', mbid: '', prefix: 'LIM'},
{name: 'arcadia lifestyle', country: 'GB', mbid: '', prefix: 'LS'},
{name: 'arcadia loop academy', country: 'GB', mbid: '', prefix: 'LA'},
{name: 'arcadia mastertrax', country: 'GB', mbid: '', prefix: 'MT'},
{name: 'arcadia maxmusic', country: 'GB', mbid: '', prefix: 'MAX'},
{name: 'arcadia media music', country: 'GB', mbid: 'd3fc0c98-f9f6-4b9e-bce1-74ce44d76a90', prefix: 'MM'},
{name: 'arcadia minimal', country: 'GB', mbid: '', prefix: 'AMI'},
{name: 'arcadia national', country: 'GB', mbid: '', prefix: 'AN'},
{name: 'arcadia shorts', country: 'GB', mbid: '', prefix: 'AS'},
{name: 'arcadia spot leitmotif', country: 'GB', mbid: '', prefix: 'SPOT'},
{name: 'arcadia therapy', country: 'GB', mbid: '', prefix: 'T'},
{name: 'arcadia viva', country: 'GB', mbid: '', prefix: 'VIV'},
{name: 'arrow production music', country: '', mbid: '', prefix: 'ARW'},
{name: 'art melodies', country: 'FR', mbid: '', prefix: 'EOS'},
{name: 'a-tension', country: 'AU', mbid: '', prefix: 'ATEN'},
{name: 'a-tone', country: 'GB', mbid: '', prefix: 'ATN'},
{name: 'attitude', country: '', mbid: '', prefix: 'ATT'},
{name: 'audia', country: '', mbid: '', prefix: 'AUDIA'},
{name: 'audio addiction', country: 'US', mbid: '', prefix: 'AAM'},
{name: 'axs documentary', country: 'FR', mbid: '', prefix: 'AXD'},
{name: 'ax\'s music', country: 'FR', mbid: 'b445d172-9daa-4543-916e-8efd8e6f5225', prefix: 'AXS'},
{name: 'ax\'s world', country: 'FR', mbid: '', prefix: 'AXW'},
{name: 'axs world', country: 'FR', mbid: '', prefix: 'AXW'},
{name: 'bandit', country: '', mbid: '379b9e21-8672-4f35-a4b6-070b3177c0c0', prefix: 'BPM'},
{name: 'beat bites', country: 'US', mbid: '636894f3-c482-4e21-9a43-3990632663fe', prefix: 'BB'},
{name: 'beatbox', country: 'AU', mbid: 'de05ab86-1ef9-4dd9-8f82-206507365040', prefix: 'BBX'},
{name: 'beatclock productions', country: '', mbid: '', prefix: 'BCB'},
{name: 'beatfix', country: '', mbid: '', prefix: 'BFX'},
{name: 'beats fresh', country: '', mbid: '', prefix: 'BF'},
{name: 'beats planet', country: '', mbid: '', prefix: 'BP'},
{name: 'bed heads music', country: 'US', mbid: '', prefix: 'BHM'},
{name: 'beds & beats', country: '', mbid: '', prefix: 'BNB'},
{name: 'bibliotheque music', country: '', mbid: '', prefix: 'BIBTQ'},
{name: 'big idea music', country: 'US', mbid: '', prefix: 'BIM'},
{name: 'big screen music', country: '', mbid: '83a77028-5c3d-40c7-ab59-b8fb61702752', prefix: 'BSM'},
{name: 'black octopus music', country: 'FR', mbid: '', prefix: 'BLOM'},
{name: 'black red gold', country: '', mbid: '', prefix: 'BRG'},
{name: 'blazed out music', country: '', mbid: '3c5f7ddf-cc94-4a04-aff1-68be0f42d06c', prefix: 'BOM'},
{name: 'blind colour', country: '', mbid: '', prefix: 'BC'},
{name: 'boost tv', country: '', mbid: 'bd71628b-3a10-43ae-aa54-6c64080c1ac6', prefix: 'BOOST TV'},
{name: 'boston bay records', country: 'US', mbid: '', prefix: 'BBR'},
{name: 'brand x music', country: 'US', mbid: '7cd4c0ce-0669-4ef1-a265-7649e3ea1aff', prefix: 'BDM'},
{name: 'brand x music', country: 'US', mbid: '7cd4c0ce-0669-4ef1-a265-7649e3ea1aff', prefix: 'BXMT'},
{name: 'build destroy music', country: 'US', mbid: '', prefix: 'BDM'},
{name: 'cavendish archive', country: '', mbid: '', prefix: 'CAVA'},
{name: 'cavendish classical', country: 'GB', mbid: '89cc9b5d-9c89-44ff-a2f6-1eab2919b3d8', prefix: 'CACL'},
{name: 'cavendish classical', country: 'GB', mbid: '8ed0bb0a-1883-41bb-93e4-21c2cabb92ef', prefix: 'CACL'},
{name: 'cavendish music', country: 'GB', mbid: 'b7a82c40-36b7-445a-a5c3-c4f453193ff6', prefix: 'CAV-CD'},
{name: 'cavendish trailers', country: 'GB', mbid: '92ff2893-6ce0-402f-b662-7ae0811f44ff', prefix: 'CAVT'},
{name: 'cezame carte blanche', country: 'FR', mbid: 'debe07e0-a2b0-4e26-9735-27ba8695b764', prefix: 'CCB'},
{name: 'cezame', country: 'FR', mbid: 'e6f0f3a1-502f-4a2e-bd18-5721319676e3', prefix: 'CEZ'},
{name: 'cezame global investigation', country: 'FR', mbid: '110575f3-7bc6-4723-9bd2-bb021a24a233', prefix: 'CEG'},
{name: 'cezame original scores', country: 'FR', mbid: 'bf895fe2-6fae-4611-a040-62d0d0761f20', prefix: 'CEO'},
{name: 'cezame trailers', country: 'FR', mbid: '812eb9a1-e461-430c-b203-019b3698e7ed', prefix: 'CET'},
{name: 'cezame virtual', country: 'FR', mbid: '3b4cd53e-d653-4f62-8895-6f20de276e53', prefix: 'CEV'},
{name: 'chapel of rock', country: 'GB', mbid: '', prefix: 'CHR'},
{name: 'chroma', country: '', mbid: '', prefix: 'CM'},
{name: 'chroma x artist series', country: '', mbid: '', prefix: 'CMXA'},
{name: 'chroma x', country: '', mbid: '', prefix: 'CMX'},
{name: 'cinematic tracks', country: '', mbid: '', prefix: 'CT'},
{name: 'cinetrax', country: '', mbid: 'ef9da969-9aea-4b48-aead-6849afd1e03d', prefix: 'CTRX'},
{name: 'classik', country: '', mbid: '', prefix: 'CLASSIK'},
{name: 'clockwork orange', country: '', mbid: '', prefix: 'COM'},
{name: 'commercials non stop', country: '', mbid: '382a446e-f49f-4dec-a25b-713b9d095551', prefix: 'CNS'},
{name: 'cosmind', country: '', mbid: '', prefix: 'CPM'},
{name: 'counter music', country: '', mbid: '', prefix: 'CTR'},
{name: 'crack-up music', country: 'AU', mbid: '', prefix: 'CRKU'},
{name: 'crimesonics', country: '', mbid: '', prefix: 'CSV'},
{name: 'critical mass', country: '', mbid: '', prefix: 'CRM'},
{name: 'crossbreed music', country: '', mbid: '', prefix: 'CRB'},
{name: 'cue', country: '', mbid: '', prefix: 'CUE'},
{name: 'cypher tm', country: '', mbid: '', prefix: 'CYPT'},
{name: 'dancing about architecture', country: '', mbid: '', prefix: 'DAA'},
{name: 'deep east music', country: '', mbid: '', prefix: 'DEM'},
{name: 'deneb', country: 'IT', mbid: '1c9fc74a-6645-4977-b143-e2d60464536e', prefix: 'DNB'},
{name: 'dig it', country: '', mbid: '', prefix: 'DGT'},
{name: 'directors cuts', country: 'GB', mbid: 'a8cf69d2-e4c6-41ce-8a73-6bf5102f44c4', prefix: 'DCD'},
{name: 'dynamic music', country: '', mbid: '', prefix: 'DM'},
{name: 'earmotion', country: 'DE', mbid: '', prefix: 'EAR'},
{name: 'ear parade', country: '', mbid: '', prefix: 'EPM'},
{name: 'earth tones', country: 'GB', mbid: '539eb12d-3328-4de0-8e6d-94ccd320c943', prefix: 'XET'},
{name: 'egg music', country: '', mbid: '', prefix: 'EGG'},
{name: 'encore merci', country: 'FR', mbid: '', prefix: 'EM'},
{name: 'enginuity music', country: 'US', mbid: '', prefix: 'ENG'},
{name: 'epic', country: '', mbid: '', prefix: 'EPC'},
{name: 'epic score', country: '', mbid: 'c0f23fba-33e9-4726-a4df-a4ba5ec9616a', prefix: 'ES'},
{name: 'evolving sound', country: '', mbid: '', prefix: 'EVS'},
{name: 'extreme easy listening', country: 'GB', mbid: '', prefix: 'XEL'},
{name: 'extreme twisted', country: 'GB', mbid: '55c088c6-db2f-404a-9508-db075a0f9734', prefix: 'XTW'},
{name: 'eyeballs & eardrums', country: '', mbid: '', prefix: 'E&E'},
{name: 'fantasy classical collection', country: '', mbid: '', prefix: 'CLXY'},
{name: 'fantasy documentary series', country: '', mbid: '', prefix: 'IDOCS'},
{name: 'fantasy easy listening', country: '', mbid: '', prefix: 'EZLY'},
{name: 'fantasy film series', country: '', mbid: '', prefix: 'FEXY'},
{name: 'fantasy music', country: '', mbid: '', prefix: 'SEXY'},
{name: 'felt archives', country: '', mbid: '', prefix: 'FML ARC'},
{name: 'felt christmas', country: '', mbid: '', prefix: 'FML CH'},
{name: 'felt classical masters', country: '', mbid: '', prefix: 'FML CM'},
{name: 'felt contemporary', country: '', mbid: '', prefix: 'FML FC'},
{name: 'felt cuckooland', country: '', mbid: '', prefix: 'FML CK'},
{name: 'felt off to battle', country: '', mbid: '', prefix: 'FML OTB'},
{name: 'felt orchestral & score', country: '', mbid: '', prefix: 'FML OS'},
{name: 'felt sound circle', country: '', mbid: '', prefix: 'FML SC'},
{name: 'felt soundworks', country: '', mbid: '', prefix: 'FML SND'},
{name: 'felt themes', country: '', mbid: '', prefix: 'FML TH'},
{name: 'felt trailer', country: '', mbid: '', prefix: 'FML TR'},
{name: 'felt vintage', country: '', mbid: '', prefix: 'FML VN'},
{name: 'felt world', country: '', mbid: '', prefix: 'FML WR'},
{name: 'flava of the month', country: '', mbid: 'cbaad7de-91ee-473b-91c5-af328f553fd5', prefix: 'FLAVA'},
{name: 'float music', country: '', mbid: '', prefix: 'FL'},
{name: 'foxhole records', country: '', mbid: '', prefix: 'FOX'},
{name: 'future pop', country: '', mbid: '', prefix: 'FUP'},
{name: 'global graffiti', country: 'US', mbid: '', prefix: 'GGM'},
{name: 'gore & audio', country: 'GB', mbid: '9fabdd31-32af-41b8-a0ad-f790fb5b1d3e', prefix: 'GAA'},
{name: 'gothic hybrid', country: '', mbid: '', prefix: 'GHY'},
{name: 'gothic storm', country: '', mbid: 'fbd30909-70f6-4d53-861a-75016740cf06', prefix: 'GOTHIC'},
{name: 'gothic storm\'s toolworks', country: '', mbid: '', prefix: 'GTW'},
{name: 'grandmaster', country: 'GB', mbid: '75892da4-7d87-44f4-b502-1e0a60f466e3', prefix: 'XGM'},
{name: 'gsound', country: '', mbid: '', prefix: 'GSOUND'},
{name: 'gum collections', country: 'FR', mbid: '4398ff35-41ec-4a35-aa40-d6b660841856', prefix: 'GUM'},
{name: 'gum motion tracks', country: 'FR', mbid: '', prefix: 'GMT'},
{name: 'happy records', country: '', mbid: '03c8fc38-c46f-418b-9da7-3ba47de157b7', prefix: 'HR'},
{name: 'heavy melody trailers', country: '', mbid: '', prefix: 'HMT'},
{name: 'heavy promos', country: '', mbid: '351ea7da-0ed9-469e-b4cb-7704725d3ab4', prefix: 'HP'},
{name: 'heavy promos sound design', country: '', mbid: '', prefix: 'HPFX'},
{name: 'hen\'s teeth music', country: '', mbid: 'd794fced-59b4-482e-891b-534470c422a4', prefix: 'HTM'},
{name: 'homegrown', country: '', mbid: '', prefix: 'HOME'},
{name: 'hypekit', country: '', mbid: '', prefix: 'HK'},
{name: 'hype music', country: 'GB', mbid: '90997446-f34b-4858-89d9-c3a22b5a22fa', prefix: 'HYP'},
{name: 'hyperlocal', country: 'US', mbid: '', prefix: 'HL'},
{name: 'iliad - beach road music', country: 'US', mbid: '', prefix: 'ILD'},
{name: 'immediate music', country: '', mbid: '53574995-44bf-4656-a70f-25e040b4ac87', prefix: 'IMX'},
{name: 'immortal music', country: '', mbid: '', prefix: 'IMM'},
{name: 'i\'m not a machine music', country: '', mbid: '', prefix: 'INAMM'},
{name: 'impact trailer music', country: 'US', mbid: '', prefix: 'ITMCD'},
{name: 'impulsion', country: 'CA', mbid: '', prefix: 'IMP'},
{name: 'indiesonics', country: '', mbid: '', prefix: 'IND'},
{name: 'in pictures', country: '', mbid: '', prefix: 'INPIC'},
{name: 'in-spired', country: '', mbid: '', prefix: 'IPM'},
{name: 'intah', country: 'US', mbid: '', prefix: 'INTAH'},
{name: 'intermede', country: '', mbid: '', prefix: 'INT'},
{name: 'intersound', country: '', mbid: 'be0cffb1-b3f2-465f-8753-1d27c1a10caf', prefix: 'ISCD'},
{name: 'intervox', country: '', mbid: '', prefix: 'IVOX'},
{name: 'in the groove', country: '', mbid: '', prefix: 'ITG'},
{name: 'jolt trailer music', country: '', mbid: '', prefix: 'JTM'},
{name: 'jsak', country: 'JP', mbid: '', prefix: 'JSAK'},
{name: 'justement music', country: '', mbid: '331ca2d1-337a-4c33-acac-8eb0438063bf', prefix: 'JUST'},
{name: 'jw media music', country: '', mbid: 'fac7e148-ef7a-4127-b4c0-6f6744063dc4', prefix: 'JW'},
{name: 'jw vault collection', country: '', mbid: '', prefix: 'JWV'},
{name: 'kingdom 2', country: '', mbid: '', prefix: 'KING'},
{name: 'klanglobby', country: '', mbid: '', prefix: 'KL'},
{name: 'kool kat', country: '', mbid: 'ffee822b-3112-4382-9e0c-f64f57326414', prefix: 'KAT'},
{name: 'kosinus archives', country: 'FR', mbid: '', prefix: 'KOA'},
{name: 'kosinus arts', country: 'FR', mbid: '3271de2b-e575-4940-ad05-16dad17c8f22', prefix: 'KAR'},
{name: 'kosinus classical', country: 'FR', mbid: '', prefix: 'KCL'},
{name: 'kosinus', country: 'FR', mbid: '4ceff2bb-1025-46de-bf89-2008fb41b571', prefix: 'KOS'},
{name: 'kosinus magazine', country: 'FR', mbid: 'd0aabdd2-126b-44da-ad2e-d56728c64b82', prefix: 'KOM'},
{name: 'kosinus on line', country: 'FR', mbid: '49b40560-dc37-4dda-87b0-ad4019df47ce', prefix: 'KOL'},
{name: 'koto', country: 'JP', mbid: '', prefix: 'KOTO'},
{name: 'lab rat recordings', country: 'GB', mbid: '27ffa24e-964c-49c9-b6ed-fb92e328c8cf', prefix: 'XLR'},
{name: 'law & audio', country: 'GB', mbid: '7bdc81cd-9a8a-4558-8b49-e21118111c9a', prefix: 'LAA'},
{name: 'library of the human soul', country: '', mbid: '', prefix: 'LHS'},
{name: 'liftmusic', country: '', mbid: 'b924fe83-f68a-4882-add2-21e436d70892', prefix: 'LIFT'},
{name: 'liftmusic factual', country: '', mbid: '', prefix: 'FACT'},
{name: 'liftmusic wildcards', country: '', mbid: '0c54ff07-6977-4854-bad0-d795775fa13c', prefix: 'WILD'},
{name: 'lmntl records', country: '', mbid: '', prefix: 'LMTL'},
{name: 'lovely music', country: '', mbid: '', prefix: 'LVM'},
{name: 'made', country: 'GB', mbid: '3de919f1-1672-4a33-9cb7-cc0019e3f696', prefix: 'MDE'},
{name: 'magazine records', country: 'FR', mbid: '', prefix: 'MR'},
{name: 'magnetic records', country: 'FR', mbid: '', prefix: 'MAG'},
{name: 'marquee music', country: 'US', mbid: '203004cc-1fba-4847-9f89-140a17f81196', prefix: 'MQ'},
{name: 'megatrax', country: 'US', mbid: 'a82773f8-8f6d-483f-9b2a-3fdc0d0d4418', prefix: 'MX'},
{name: 'mexican music library', country: '', mbid: '', prefix: 'MML'},
{name: 'minds and music', country: '', mbid: '9d791422-9236-4776-94cb-48f908f651b5', prefix: 'MAM'},
{name: 'minim', country: '', mbid: '', prefix: 'MNM'},
{name: 'misszik', country: '', mbid: '', prefix: 'MISSZIK'},
{name: 'mixtape', country: 'GB', mbid: 'a53f5586-e75a-4ab3-b40f-f1c30e7414a9', prefix: 'XMT'},
{name: 'modus operandi', country: '', mbid: 'fce6b313-d3ba-43a2-af77-630d55683c2d', prefix: 'MOPM'},
{name: 'montage music', country: '', mbid: '', prefix: 'MMX'},
{name: 'montmorency records', country: '', mbid: '92c2d46a-71d9-4bf7-b390-d4b5c5a6b8b1', prefix: 'MYR'},
{name: 'muse', country: '', mbid: '', prefix: 'MUSE'},
{name: 'musica britannica', country: '', mbid: '', prefix: 'ESL-MB'},
{name: 'musical concepts', country: 'US', mbid: '7e515f97-54f8-4ac6-ba74-922fd8df0109', prefix: 'MCCD'},
{name: 'music beyond', country: '', mbid: '32183667-f5e9-4a0d-8df3-fba12f2ffa62', prefix: 'BYND'},
{name: 'musicbox classics', country: '', mbid: '', prefix: 'MBC'},
{name: 'musicbox', country: '', mbid: '', prefix: 'MB'},
{name: 'music for productions', country: 'CA', mbid: '', prefix: 'MFP'},
{name: 'music gallery', country: 'FR', mbid: 'b8af9d25-ea43-446b-9e81-693d01c0376c', prefix: 'MG'},
{name: 'music shop', country: 'FR', mbid: '4dc92454-5ea6-468b-83ec-c925efd930d4', prefix: ''},
{name: 'music shop online', country: 'FR', mbid: '', prefix: 'MSO'},
{name: 'music shop tools', country: 'FR', mbid: '688d3f7a-5347-4c81-97e0-b30a080f7381', prefix: 'MT'},
{name: 'music shop zen', country: 'FR', mbid: '9a12fd69-2845-4aa9-b893-0d70d4a65761', prefix: 'ZEN'},
{name: 'musique & music', country: '', mbid: 'af3a2ccd-b66e-4d9d-b33d-394c8319a93f', prefix: 'ZIK'},
{name: 'must save jane', country: '', mbid: '', prefix: 'MSJ'},
{name: 'muzikotek', country: '', mbid: '', prefix: 'MUZ'},
{name: 'nelvana', country: '', mbid: '', prefix: 'NLV'},
{name: 'new west studios scoring collection', country: '', mbid: '', prefix: 'NWS'},
{name: 'ninja tune production music', country: '', mbid: '', prefix: 'NTPM'},
{name: 'nova nota', country: '', mbid: '470d76d3-12f4-4e28-bbe3-02a911c05be6', prefix: 'NVN'},
{name: 'octopus', country: 'IT', mbid: 'b2aa62e5-98bd-4a4d-802c-b65c0eb40645', prefix: 'OTP'},
{name: 'opus1', country: 'US', mbid: '', prefix: 'OPUS'},
{name: 'organic spark', country: '', mbid: '1223b8f8-b255-404a-a23b-7a3a7d1710da', prefix: 'OSPK'},
{name: 'ours music', country: 'FR', mbid: '', prefix: 'OML'},
{name: 'parigo', country: 'FR', mbid: '9975785f-d31d-4031-944f-0527d0a2649f', prefix: 'PGO'},
{name: 'parry classical', country: '', mbid: '', prefix: 'PMC'},
{name: 'parry music library', country: '', mbid: '', prefix: 'PML'},
{name: 'passport', country: 'GB', mbid: 'e67cd690-64a7-429e-a68a-f999b879a34a', prefix: 'XPS'},
{name: 'pedigree cuts', country: '', mbid: '52d7fc99-6cfd-4738-98ad-b722248a83df', prefix: 'PED'},
{name: 'pennybank tunes', country: 'FR', mbid: '0251b61b-7545-4bc0-b487-975ef6db2857', prefix: 'PNBT'},
{name: 'pennybank tunes profiles', country: 'FR', mbid: '', prefix: 'PNBP'},
{name: 'picture puncture', country: '', mbid: '', prefix: 'PICX'},
{name: 'pitchhammer', country: '', mbid: '', prefix: 'PTCH'},
{name: 'playground hollywood', country: '', mbid: '6b7a2131-3d71-4e90-b2ab-a61ec215c8aa', prefix: 'PGH'},
{name: 'playlist', country: '', mbid: '', prefix: 'PLAY'},
{name: 'poke music', country: '', mbid: 'e9f6d244-3973-49b1-8e1e-bd0c307f8e1b', prefix: 'POKE'},
{name: 'popcorn music', country: '', mbid: '', prefix: 'POPC'},
{name: 'post production music', country: '', mbid: 'd2ce9db0-ae06-4643-b23b-9087b90b3aff', prefix: 'PPM'},
{name: 'pp music', country: '', mbid: '56ea4f9c-11a1-4d14-ab37-894fd6aebf37', prefix: 'PP'},
{name: 'primrose', country: 'IT', mbid: '10cf67f3-6fbe-4155-831c-05922b83d5aa', prefix: 'PRCD'},
{name: 'production music online', country: '', mbid: 'ee0bc306-f4db-492e-9c75-173b2475fbf1', prefix: 'PMOL'},
{name: 'promobox', country: '', mbid: '86f6efc7-8378-49eb-a7d7-2ac221da59fc', prefix: 'PB'},
{name: 'pro viva', country: '', mbid: '', prefix: 'ISPV'},
{name: 'pure music', country: 'US', mbid: '', prefix: 'PURM'},
{name: 'püsh pop', country: '', mbid: '', prefix: 'PPOP'},
{name: 'q-factory', country: '', mbid: 'dc3a51a3-685b-4e5a-a454-61e7debf0d9d', prefix: 'REP'},
{name: 'q-series', country: 'GB', mbid: '800772a0-4e3f-4ef8-a826-0e4cc3faacf9', prefix: 'QCD'},
{name: 'quest', country: 'GB', mbid: '', prefix: 'QWP'},
{name: 'ready made production', country: 'FR', mbid: '', prefix: 'RMP'},
{name: 'reality check', country: 'GB', mbid: 'a82773f8-8f6d-483f-9b2a-3fdc0d0d4418', prefix: 'XRC'},
{name: 'redcola', country: 'US', mbid: '24f34b1b-b453-4c53-bc84-aa3d5c6e8386', prefix: 'RC'},
{name: 'rogue souls', country: '', mbid: '', prefix: 'ROG'},
{name: 'sak', country: 'JP', mbid: '', prefix: 'SAK'},
{name: 'sauce music', country: '', mbid: '3ff42e9b-d203-4ae9-92db-5aa6fcec41a0', prefix: 'SM'},
{name: 'scorched score', country: '', mbid: '', prefix: 'SCR'},
{name: 'score', country: '', mbid: '', prefix: 'SCORE'},
{name: 'scoreganics', country: 'GB', mbid: '3b3bd441-5082-421b-9234-a7f48a1ab3b9', prefix: 'SCS'},
{name: 'selectracks instrumental catalog', country: '', mbid: '', prefix: 'ST'},
{name: 'selectracks song catalog', country: '', mbid: '', prefix: 'SC'},
{name: 'sensacion', country: 'US', mbid: '9131495c-a406-4241-98e9-455ceefd3b19', prefix: 'SN'},
{name: 'shock files', country: 'US', mbid: '', prefix: 'SKF'},
{name: 'sick muse music', country: '', mbid: '', prefix: 'SMM '},
{name: 'silver screen', country: '', mbid: '', prefix: 'SIL'},
{name: 'songcraft', country: '', mbid: '', prefix: 'SONG'},
{name: 'sonia classics', country: '', mbid: '', prefix: 'SONIA'},
{name: 'sonic artefact', country: '', mbid: '', prefix: 'SA'},
{name: 'sonic symphony', country: 'US', mbid: '75c4abbb-670d-4320-805f-7617eb729697', prefix: 'SSY'},
{name: 'sonoton authentic series', country: '', mbid: '140a26d4-6632-41cb-b0af-d3a061242faa', prefix: 'SAS'},
{name: 'sonoton classical', country: '', mbid: '4d5e4398-c966-49d8-a2f0-300794e5cbfe', prefix: 'SCDC'},
{name: 'sonoton', country: '', mbid: '30864815-1104-466d-8900-5a8baaa2203b', prefix: 'SCD'},
{name: 'sonoton rockshop', country: '', mbid: '', prefix: 'SCD RCK'},
{name: 'sonoton trailer tracks', country: '', mbid: '3a3c068f-854e-4a04-b8d7-d11aa9a80c01', prefix: 'STT'},
{name: 'sonoton trailer tracks virtual', country: '', mbid: '695a9672-7937-4da1-83ef-809678bb1209', prefix: 'STTV'},
{name: 'sonoton vanguard', country: '', mbid: '', prefix: 'SCDV'},
{name: 'soulstudio7', country: 'US', mbid: '', prefix: 'SSS'},
{name: 'sound adventures', country: 'CH', mbid: '9fabdd31-32af-41b8-a0ad-f790fb5b1d3e', prefix: 'SAV'},
{name: 'sound music album', country: '', mbid: '3db99f45-3675-48e6-a6ec-36dece2ec1de', prefix: 'SMA'},
{name: 'source in sync', country: 'US', mbid: '0e5aa0f9-2988-4096-808a-eafdc1044a79', prefix: 'SIS'},
{name: 'sparse music', country: 'DE', mbid: '', prefix: 'SPRS'},
{name: 'spider cues', country: 'US', mbid: '651f7254-4552-47e4-94ff-921ae9cec72e', prefix: 'SQE'},
{name: 'spintrest', country: 'GB', mbid: '', prefix: 'SPN'},
{name: 'stampede', country: 'GB', mbid: '47967ba5-046f-4249-947a-ce5ab93f1cca', prefix: 'XST'},
{name: 'standard music', country: '', mbid: '', prefix: 'ESL'},
{name: 'stereoroyal', country: '', mbid: '87b39159-15b7-4ea1-a04d-3076e202f92c', prefix: 'STR'},
{name: 'stereoscopic', country: '', mbid: '', prefix: 'SCOP'},
{name: 'strip sounds', country: '', mbid: '4784a6bb-716e-4395-8263-ff92d70eb5e8', prefix: 'STRP'},
{name: 'studio g', country: '', mbid: '6ad9a8bd-fed9-4b4b-833f-50657bcaff97', prefix: 'SG'},
{name: 'sunstone recordings', country: '', mbid: '', prefix: 'SUN'},
{name: 'superfly audio', country: '', mbid: '013eea1f-bd3c-460e-99ca-aaeb153a5ffd', prefix: 'SFLY'},
{name: 'superpitch artist series', country: '', mbid: '', prefix: 'SUPIAS'},
{name: 'superpitch', country: '', mbid: '', prefix: 'SUPI'},
{name: 'superpitch drama', country: '', mbid: '', prefix: 'SUPIDR'},
{name: 'superpitch entertainment', country: '', mbid: '', prefix: 'SUPIE'},
{name: 'super pop', country: 'GB', mbid: '5a1b7fc7-d3a8-4cd2-b981-ac00718de723', prefix: 'XSP'},
{name: 'super rock', country: 'GB', mbid: 'a42f9f7f-14ec-46c9-a6ad-f65790ff5e1f', prefix: 'XSR'},
{name: 'superstore', country: '', mbid: '', prefix: 'SUPER'},
{name: 'surefire', country: '', mbid: '', prefix: 'SURE'},
{name: 'syncstories', country: '', mbid: '', prefix: 'STORY'},
{name: 'telesongz', country: 'US', mbid: '', prefix: 'TLS'},
{name: 'teletunez', country: 'US', mbid: '', prefix: 'TT'},
{name: 'that\'s amore', country: 'IT', mbid: '', prefix: 'TA'},
{name: 'the 13 brotherhood', country: 'GB', mbid: '78d8439b-8ca5-4e95-bc94-ecdd71aa0779', prefix: 'XXL'},
{name: 'the box', country: '', mbid: '', prefix: 'TBX'},
{name: 'the den', country: '', mbid: '', prefix: 'DEN'},
{name: 'the devil\'s cut', country: 'GB', mbid: '954d0b12-8129-4d21-b0c6-579821c6dc3f', prefix: 'XDC'},
{name: 'the film music of ronald stein', country: '', mbid: '', prefix: 'RS'},
{name: 'the funky junkies', country: '', mbid: 'a390061b-5e08-403a-a8b0-193c48d78a2b', prefix: 'TFJ'},
{name: 'the moonshine music', country: 'GB', mbid: 'bf6461c0-2543-4274-a7f2-02a8d1fff4de', prefix: 'XXX'},
{name: 'the perfect music library', country: 'GB', mbid: '', prefix: 'TPML'},
{name: 'the scene', country: 'US', mbid: '86021d16-0816-4ce6-8ca1-1a33d0aaf6d2', prefix: 'TS'},
{name: 'third rail', country: '', mbid: '', prefix: 'IIIR'},
{name: 'three ingredients or less', country: '', mbid: '4281c5b5-bca9-4f57-a4a1-2300ba12ff74', prefix: '3ING'},
{name: 'tonal injection', country: 'US', mbid: '8ed0bb0a-1883-41bb-93e4-21c2cabb92ef', prefix: 'TI'},
{name: 'track distillery', country: 'US', mbid: '', prefix: 'TD'},
{name: 'trax4pro', country: '', mbid: '', prefix: 'TX'},
{name: 'trede collection', country: '', mbid: '', prefix: 'TREDE'},
{name: 'tubesounds', country: '', mbid: '', prefix: 'TUBE'},
{name: 'twisted jukebox', country: '', mbid: 'fb98bbda-e442-49d0-86fe-abe482251ab9', prefix: 'TJ'},
{name: 'two steps from hell', country: 'GB', mbid: '349e2e06-6b9d-4f79-bb15-c9320a59798c', prefix: 'XTS'},
{name: 'ultimate classix', country: 'GB', mbid: '48398802-88f0-439f-af08-ab941b1f28ab', prefix: 'XCL'},
{name: 'ultraphonic', country: '', mbid: 'ef107e0a-47cf-47d0-a6fe-1317b9f5fc6b', prefix: 'UPMCD'},
{name: 'underscore', country: '', mbid: '', prefix: 'UND'},
{name: 'vadzimu', country: '', mbid: '', prefix: 'VAD'},
{name: 'valentino', country: '', mbid: '', prefix: 'VT'},
{name: 'velvet ears', country: 'GB', mbid: '09166de7-dfd1-4ff1-aa81-801a708a9c13', prefix: 'VEX'},
{name: 'vibey', country: '', mbid: '', prefix: 'VIBEY'},
{name: 'vibey underscores', country: '', mbid: '', prefix: 'UN'},
{name: 'vibrant music', country: 'GB', mbid: '', prefix: 'VIBE'},
{name: 'war & audio', country: 'GB', mbid: '922eb96d-8276-4472-a1d6-4bdc059b12c6', prefix: 'WAA'},
{name: 'who did that music', country: 'US', mbid: '70f78d17-dc81-4484-a650-bcd7cda3b156', prefix: 'TL'},
{name: 'wotnot', country: '', mbid: '', prefix: 'WN'},
{name: 'wrong planet', country: 'GB', mbid: '', prefix: 'WPM'},
{name: 'x-it music', country: '', mbid: '', prefix: 'XIT'},
{name: 'x-ray dog', country: '', mbid: '', prefix: 'XRCD'},
{name: 'x-series', country: 'GB', mbid: '23b61da0-5510-4616-b6fe-5224d34ac3ac', prefix: 'XCD'},
{name: 'zest music', country: '', mbid: '', prefix: 'ZEST'},
{name: 'zone', country: '', mbid: '7f013ad1-3232-4525-9702-70464015ca5b', prefix: 'ZONE'},
{name: 'zone plus', country: '', mbid: 'c8b34ba3-9c56-4fbf-bc3c-8a7751f92fed', prefix: 'ZONE PLUS'},
{name: 'zone trailers', country: '', mbid: '', prefix: 'ZTR'}
];
