// ==UserScript==
/* globals      ß */
// @name        Label dictionary
// @version     2019.5.6.0
// @namespace   https: //github.com/brianfreud
// @downloadURL https: //raw.githubusercontent.com/brianfreud/Userscripts/edit/master/dict_labels.js
// @updateURL   https: //raw.githubusercontent.com/brianfreud/Userscripts/edit/master/dict_labels.js
// ==/UserScript==

// handy master prefix list: https://pmamusic.com/all-prefixes/

ß.labelDB = [
{name: `101 dark orchid`, country: ``, mbid: ``, prefix: `101DOM`},
{name: `101 dark orchid music`, country: ``, mbid: ``, prefix: `101DOM`},
{name: `101 music`, country: ``, mbid: ``, prefix: `101M`},
{name: `101pm`, country: `AU`, mbid: ``, prefix: `101PM`},
{name: `101 production music`, country: `AU`, mbid: ``, prefix: `101PM`},
{name: `1 revolution music`, country: ``, mbid: `b9e5d8b4-44fa-4f79-b72d-435e52036a65`, prefix: `1RM`},
{name: `1vu music`, country: ``, mbid: ``, prefix: ``},
{name: `2nd foundation music`, country: ``, mbid: ``, prefix: `2FM`},
{name: `405 music`, country: ``, mbid: ``, prefix: ``},
{name: `411 artist series`, country: ``, mbid: ``, prefix: ``},
{name: `411 production music`, country: ``, mbid: ``, prefix: ``},
{name: `411 trailer music`, country: ``, mbid: ``, prefix: ``},
{name: `411 underscore`, country: ``, mbid: ``, prefix: ``},
{name: `42 records`, country: ``, mbid: ``, prefix: `42`},
{name: `4 elements music`, country: `US`, mbid: ``, prefix: `4EM`},
{name: `5 alarm music`, country: ``, mbid: `816c750d-9178-4dc0-b74f-d8ac08c3df95`, prefix: ``},
{name: `5 senses music artist`, country: ``, mbid: ``, prefix: ``},
{name: `5 senses music`, country: ``, mbid: ``, prefix: ``},
{name: `615 platinum series`, country: ``, mbid: `3b45dc8b-40f6-4efc-a980-12443bcfd130`, prefix: ``},
{name: `9 lives music`, country: ``, mbid: `5a813804-f8ba-4d79-9818-4d4a8f3833d8`, prefix: `NLM`},
{name: `abaco music`, country: ``, mbid: `d595bbf8-1be3-41d1-83f8-c871b39082d2`, prefix: `AB`},
{name: `abaco music`, country: ``, mbid: `d595bbf8-1be3-41d1-83f8-c871b39082d2`, prefix: `AB-CD`},
{name: `abaco music library`, country: ``, mbid: `d595bbf8-1be3-41d1-83f8-c871b39082d2`, prefix: ``},
{name: `absolute music`, country: `GB`, mbid: ``, prefix: `ABS`},
{name: `absolute music library`, country: ``, mbid: ``, prefix: ``},
{name: `acoustitracks`, country: ``, mbid: `5c83f1ea-c8e6-445b-bf58-5665e6d3752e`, prefix: ``},
{name: `active music library`, country: ``, mbid: ``, prefix: ``},
{name: `adrenalin`, country: `AU`, mbid: `b8af9d25-ea43-446b-9e81-693d01c0376c`, prefix: `AD`},
{name: `adrenalin production music library`, country: ``, mbid: `b8af9d25-ea43-446b-9e81-693d01c0376c`, prefix: ``},
{name: `adrenalin sounds`, country: ``, mbid: `176a60fb-4dd9-4fd3-a0bb-99f5e10febb0`, prefix: ``},
{name: `adrenalin vocals`, country: `AU`, mbid: ``, prefix: `ADV`},
{name: `african planit`, country: ``, mbid: ``, prefix: ``},
{name: `afro dizzy`, country: ``, mbid: ``, prefix: `ADZ`},
{name: `afro musique`, country: ``, mbid: `995ab52b-c2c4-4206-a10c-6ced001ed5b1`, prefix: `AFRO`},
{name: `alchemy music`, country: ``, mbid: ``, prefix: ``},
{name: `alchemy trailer tools`, country: ``, mbid: ``, prefix: ``},
{name: `algo records`, country: ``, mbid: ``, prefix: ``},
{name: `allmusicgallery`, country: ``, mbid: ``, prefix: ``},
{name: `all sorts music`, country: ``, mbid: ``, prefix: ``},
{name: `altitude music`, country: ``, mbid: `9d1c8f0c-fc86-4d5e-a41c-1ce530f4c473`, prefix: `ALT`},
{name: `altitude underscore`, country: ``, mbid: ``, prefix: `AU`},
{name: `altitude x faber`, country: ``, mbid: ``, prefix: `AXF`},
{name: `amped`, country: ``, mbid: ``, prefix: `AMPD`},
{name: `amphibious zoo`, country: ``, mbid: `edf2b729-f214-4f0a-9fa3-0acec31fa22f`, prefix: ``},
{name: `amplitude`, country: `AU`, mbid: `ac0193ee-ff6d-4e93-b62b-c46b9a685605`, prefix: `AMPT`},
{name: `amusicom`, country: `US`, mbid: `10cf67f3-6fbe-4155-831c-05922b83d5aa`, prefix: `AM`},
{name: `amygdala music`, country: ``, mbid: `109c7f31-a6e6-45f4-933e-888d2def9e22`, prefix: `AMY`},
{name: `analog champion`, country: ``, mbid: ``, prefix: `ACPM`},
{name: `anarchy music`, country: ``, mbid: `a69e7793-62db-4186-8ff0-8688e4674609`, prefix: `ANM`},
{name: `and then some`, country: ``, mbid: ``, prefix: `ATS`},
{name: `anno domini nation`, country: ``, mbid: ``, prefix: `AD`},
{name: `anonymous recordings`, country: ``, mbid: ``, prefix: `AR`},
{name: `arcadia cinematic`, country: `GB`, mbid: ``, prefix: `AC`},
{name: `arcadia classical media music`, country: `GB`, mbid: ``, prefix: `CMC`},
{name: `arcadia cosmos`, country: `GB`, mbid: ``, prefix: `375`},
{name: `arcadia cosmos special select`, country: `GB`, mbid: ``, prefix: `COS`},
{name: `arcadia deluxe`, country: `GB`, mbid: ``, prefix: `DL`},
{name: `arcadia drones`, country: `GB`, mbid: ``, prefix: `ARD`},
{name: `arcadia envogue`, country: `GB`, mbid: ``, prefix: `ENV`},
{name: `arcadia esovision`, country: `GB`, mbid: ``, prefix: `EV`},
{name: `arcadia galaxy music lexicon`, country: `GB`, mbid: ``, prefix: `GML`},
{name: `arcadia global authentic music`, country: `GB`, mbid: ``, prefix: `GAM`},
{name: `arcadia hollywood`, country: `GB`, mbid: ``, prefix: `HSMS`},
{name: `arcadia jazz line`, country: `GB`, mbid: ``, prefix: `JL`},
{name: `arcadia jingle bank`, country: `GB`, mbid: ``, prefix: `AJB`},
{name: `arcadia less-is-more`, country: `GB`, mbid: ``, prefix: `LIM`},
{name: `arcadia lifestyle`, country: `GB`, mbid: ``, prefix: `LS`},
{name: `arcadia loop academy`, country: `GB`, mbid: ``, prefix: `LA`},
{name: `arcadia mastertrax`, country: `GB`, mbid: ``, prefix: `MT`},
{name: `arcadia maxmusic`, country: `GB`, mbid: ``, prefix: `MAX`},
{name: `arcadia media music`, country: `GB`, mbid: `de05ab86-1ef9-4dd9-8f82-206507365040`, prefix: `MM`},
{name: `arcadia minimal`, country: `GB`, mbid: ``, prefix: `AMI`},
{name: `arcadia national`, country: `GB`, mbid: ``, prefix: `AN`},
{name: `arcadia shorts`, country: `GB`, mbid: ``, prefix: `AS`},
{name: `arcadia spot leitmotif`, country: `GB`, mbid: ``, prefix: `SPOT`},
{name: `arcadia therapy`, country: `GB`, mbid: ``, prefix: `T`},
{name: `arcadia viva`, country: `GB`, mbid: ``, prefix: `VIV`},
{name: `arrow production music`, country: ``, mbid: ``, prefix: `ARW`},
{name: `artful music library`, country: ``, mbid: ``, prefix: ``},
{name: `art melodies`, country: `FR`, mbid: ``, prefix: `EOS`},
{name: `art of legend`, country: ``, mbid: ``, prefix: `AOL`},
{name: `a-tension`, country: `AU`, mbid: ``, prefix: `ATEN`},
{name: `a-tension music`, country: ``, mbid: ``, prefix: `ATEN`},
{name: `atomica music`, country: ``, mbid: ``, prefix: `ATO`},
{name: `a-tone`, country: `GB`, mbid: ``, prefix: `ATN`},
{name: `attitude`, country: ``, mbid: ``, prefix: `ATT`},
{name: `audia`, country: ``, mbid: ``, prefix: `AUDIA`},
{name: `audio active`, country: ``, mbid: ``, prefix: ``},
{name: `audio addiction`, country: `US`, mbid: ``, prefix: `AAM`},
{name: `audio addiction music`, country: ``, mbid: ``, prefix: `AAM`},
{name: `audiomachine`, country: ``, mbid: `57454353-1b5c-4666-860e-903acdf55199`, prefix: `AMO`},
{name: `audio monkey`, country: ``, mbid: ``, prefix: ``},
{name: `audio muziek produkties`, country: ``, mbid: ``, prefix: ``},
{name: `axs documentary`, country: `FR`, mbid: ``, prefix: `AXD`},
{name: `ax's music`, country: `FR`, mbid: `b577f5a1-fe0f-431f-952d-923e1f56503f`, prefix: `AXS`},
{name: `axs music`, country: ``, mbid: `b577f5a1-fe0f-431f-952d-923e1f56503f`, prefix: ``},
{name: `ax's world`, country: `FR`, mbid: ``, prefix: `AXW`},
{name: `axs world`, country: `FR`, mbid: ``, prefix: `AXW`},
{name: `bam artist series`, country: ``, mbid: ``, prefix: ``},
{name: `bam box`, country: ``, mbid: ``, prefix: ``},
{name: `bam library`, country: ``, mbid: ``, prefix: ``},
{name: `bandit`, country: ``, mbid: `379b9e21-8672-4f35-a4b6-070b3177c0c0`, prefix: `BPM`},
{name: `bart music library`, country: ``, mbid: ``, prefix: ``},
{name: `basstone`, country: ``, mbid: `aea7965c-bd03-4883-9a77-4a000a2ccc0a`, prefix: ``},
{name: `bdl`, country: ``, mbid: ``, prefix: ``},
{name: `beat bites`, country: `US`, mbid: `651f7254-4552-47e4-94ff-921ae9cec72e`, prefix: `BB`},
{name: `beatbox`, country: `AU`, mbid: `debe07e0-a2b0-4e26-9735-27ba8695b764`, prefix: `BBX`},
{name: `beatbox music`, country: ``, mbid: `debe07e0-a2b0-4e26-9735-27ba8695b764`, prefix: ``},
{name: `beatchamber records`, country: ``, mbid: ``, prefix: ``},
{name: `beatclock productions`, country: ``, mbid: ``, prefix: `BCB`},
{name: `beatfix`, country: ``, mbid: ``, prefix: `BFX`},
{name: `beats bakery`, country: ``, mbid: ``, prefix: ``},
{name: `beats fresh`, country: ``, mbid: ``, prefix: `BF`},
{name: `beats planet`, country: ``, mbid: ``, prefix: `BP`},
{name: `beat xplosion`, country: ``, mbid: ``, prefix: ``},
{name: `bed heads music`, country: `US`, mbid: ``, prefix: `BHM`},
{name: `beds & beats`, country: ``, mbid: ``, prefix: `BNB`},
{name: `bespoke records`, country: ``, mbid: ``, prefix: ``},
{name: `beta rhythm farm`, country: ``, mbid: ``, prefix: ``},
{name: `bibliotheque music`, country: ``, mbid: ``, prefix: `BIBTQ`},
{name: `big dawg music`, country: ``, mbid: ``, prefix: ``},
{name: `big idea music`, country: `US`, mbid: ``, prefix: `BIM`},
{name: `bigin music library`, country: ``, mbid: ``, prefix: ``},
{name: `big planet music`, country: ``, mbid: ``, prefix: ``},
{name: `big screen`, country: ``, mbid: ``, prefix: ``},
{name: `big screen music`, country: ``, mbid: `83a77028-5c3d-40c7-ab59-b8fb61702752`, prefix: `BSM`},
{name: `binary music`, country: ``, mbid: ``, prefix: ``},
{name: `bing bang boom music library`, country: ``, mbid: ``, prefix: ``},
{name: `bio production music`, country: ``, mbid: ``, prefix: ``},
{name: `black octopus music`, country: `FR`, mbid: ``, prefix: `BLOM`},
{name: `black red gold`, country: ``, mbid: ``, prefix: `BRG`},
{name: `blazed out music`, country: ``, mbid: `3c5f7ddf-cc94-4a04-aff1-68be0f42d06c`, prefix: `BOM`},
{name: `bleach productions`, country: ``, mbid: ``, prefix: ``},
{name: `blind colour`, country: ``, mbid: ``, prefix: `BC`},
{name: `blinq`, country: ``, mbid: ``, prefix: ``},
{name: `bl productions`, country: ``, mbid: ``, prefix: ``},
{name: `blue dot`, country: ``, mbid: ``, prefix: ``},
{name: `boom music cinematic`, country: ``, mbid: ``, prefix: ``},
{name: `boom music`, country: ``, mbid: ``, prefix: ``},
{name: `boost tv`, country: ``, mbid: `bd71628b-3a10-43ae-aa54-6c64080c1ac6`, prefix: `BOOST TV`},
{name: `boosttv`, country: ``, mbid: `f798cbd0-f849-4be5-9f2c-e7d9d8d44562`, prefix: ``},
{name: `boston bay records`, country: `US`, mbid: ``, prefix: `BBR`},
{name: `bosworth archive`, country: ``, mbid: ``, prefix: ``},
{name: `bosworth music`, country: ``, mbid: ``, prefix: ``},
{name: `brand x music`, country: `US`, mbid: `7e515f97-54f8-4ac6-ba74-922fd8df0109`, prefix: `BDM`},
{name: `brand x music`, country: `US`, mbid: `7e515f97-54f8-4ac6-ba74-922fd8df0109`, prefix: `BXMT`},
{name: `bright city`, country: ``, mbid: ``, prefix: ``},
{name: `brilliant music`, country: ``, mbid: ``, prefix: ``},
{name: `build destroy music`, country: `US`, mbid: ``, prefix: `BDM`},
{name: `burn`, country: ``, mbid: ``, prefix: ``},
{name: `cafe moondo`, country: ``, mbid: `a472e413-18ef-4601-989e-5dfd19d32868`, prefix: ``},
{name: `candy flip`, country: ``, mbid: ``, prefix: ``},
{name: `catapult music`, country: ``, mbid: ``, prefix: ``},
{name: `catch phrase`, country: ``, mbid: ``, prefix: ``},
{name: `cavendish archive`, country: ``, mbid: ``, prefix: `CAVA`},
{name: `cavendish classical`, country: `GB`, mbid: ``, prefix: `CACL`},
{name: `cavendish music`, country: `GB`, mbid: `bf6461c0-2543-4274-a7f2-02a8d1fff4de`, prefix: `CAV-CD`},
{name: `cavendish trailers`, country: `GB`, mbid: `954d0b12-8129-4d21-b0c6-579821c6dc3f`, prefix: `CAVT`},
{name: `cdm music`, country: ``, mbid: `476defa1-7b2f-4120-88ba-b03f6c35776c`, prefix: ``},
{name: `cezame carte blanche`, country: `FR`, mbid: ``, prefix: `CCB`},
{name: `cezame`, country: `FR`, mbid: ``, prefix: `CEZ`},
{name: `cezame global investigation`, country: `FR`, mbid: ``, prefix: `CEG`},
{name: `cezame original scores`, country: `FR`, mbid: ``, prefix: `CEO`},
{name: `cezame trailers`, country: `FR`, mbid: ``, prefix: `CET`},
{name: `cezame virtual`, country: `FR`, mbid: ``, prefix: `CEV`},
{name: `chapel of rock`, country: `GB`, mbid: ``, prefix: `CHR`},
{name: `chicago music library`, country: ``, mbid: ``, prefix: ``},
{name: `chroma`, country: ``, mbid: ``, prefix: `CM`},
{name: `chroma x artist series`, country: ``, mbid: ``, prefix: `CMXA`},
{name: `chroma x`, country: ``, mbid: ``, prefix: `CMX`},
{name: `cinemasounds music`, country: ``, mbid: `5b6e9986-29a7-441f-92ff-5927c943728a`, prefix: ``},
{name: `cinema sound tools`, country: ``, mbid: `0dc8003b-41f7-462e-83ae-5f5d30f85651`, prefix: ``},
{name: `cinematic tracks`, country: ``, mbid: ``, prefix: `CT`},
{name: `cinetiks production music`, country: ``, mbid: ``, prefix: ``},
{name: `cinetrax`, country: ``, mbid: `ef9da969-9aea-4b48-aead-6849afd1e03d`, prefix: `CTRX`},
{name: `classik`, country: ``, mbid: ``, prefix: `CLASSIK`},
{name: `clearside`, country: ``, mbid: ``, prefix: ``},
{name: `clear wave music`, country: ``, mbid: ``, prefix: ``},
{name: `clockwork orange`, country: ``, mbid: ``, prefix: `COM`},
{name: `clockwork orange music`, country: ``, mbid: ``, prefix: ``},
{name: `collision course music`, country: ``, mbid: ``, prefix: ``},
{name: `color tv`, country: ``, mbid: ``, prefix: ``},
{name: `commercials non stop`, country: ``, mbid: `382a446e-f49f-4dec-a25b-713b9d095551`, prefix: `CNS`},
{name: `cordovan music`, country: ``, mbid: ``, prefix: ``},
{name: `cosmind`, country: ``, mbid: ``, prefix: `CPM`},
{name: `cosmind production music`, country: ``, mbid: `cbec6b21-3434-4654-9278-5d72573c25a9`, prefix: ``},
{name: `counter music`, country: ``, mbid: ``, prefix: `CTR`},
{name: `cpm archive series`, country: ``, mbid: ``, prefix: ``},
{name: `cpm classical`, country: ``, mbid: ``, prefix: ``},
{name: `cpm`, country: ``, mbid: `88bce4c4-05c0-4b44-b34a-56ba0cff4c9f`, prefix: ``},
{name: `crack-up music`, country: `AU`, mbid: ``, prefix: `CRKU`},
{name: `cre8v media`, country: ``, mbid: ``, prefix: ``},
{name: `crimesonics`, country: ``, mbid: ``, prefix: `CSV`},
{name: `critical mass`, country: ``, mbid: ``, prefix: `CRM`},
{name: `crossbreed music`, country: ``, mbid: ``, prefix: `CRB`},
{name: `crush production music`, country: ``, mbid: ``, prefix: ``},
{name: `cue`, country: ``, mbid: ``, prefix: `CUE`},
{name: `cue source music`, country: ``, mbid: ``, prefix: ``},
{name: `cute music`, country: ``, mbid: `c7e812c4-c2e9-40be-b422-e95fdecdc437`, prefix: ``},
{name: `cypher`, country: ``, mbid: ``, prefix: ``},
{name: `cypher tm`, country: ``, mbid: ``, prefix: `CYPT`},
{name: `dancing about architecture`, country: ``, mbid: ``, prefix: `DAA`},
{name: `dark horse music`, country: ``, mbid: ``, prefix: ``},
{name: `dark horse vocal`, country: ``, mbid: ``, prefix: ``},
{name: `darwin music`, country: ``, mbid: ``, prefix: ``},
{name: `deep east music`, country: ``, mbid: ``, prefix: `DEM`},
{name: `deneb`, country: `IT`, mbid: ``, prefix: `DNB`},
{name: `deneb records`, country: ``, mbid: ``, prefix: ``},
{name: `dennis music`, country: ``, mbid: ``, prefix: ``},
{name: `digital assassin music`, country: ``, mbid: ``, prefix: ``},
{name: `dig it`, country: ``, mbid: ``, prefix: `DGT`},
{name: `directors cuts`, country: `GB`, mbid: `adc009c8-5409-4f74-8abe-cba5c381669a`, prefix: `DCD`},
{name: `discoveries`, country: ``, mbid: ``, prefix: ``},
{name: `double g studios music`, country: ``, mbid: ``, prefix: ``},
{name: `dynamic music`, country: ``, mbid: ``, prefix: `DM`},
{name: `ear drum`, country: ``, mbid: `42afc511-6faa-4ff2-b0c2-84faf5f73a3d`, prefix: ``},
{name: `earmotion audio creation`, country: ``, mbid: ``, prefix: ``},
{name: `earmotion`, country: `DE`, mbid: ``, prefix: `EAR`},
{name: `ear parade`, country: ``, mbid: ``, prefix: `EPM`},
{name: `earth tones`, country: `GB`, mbid: ``, prefix: `XET`},
{name: `ear tonic music`, country: ``, mbid: ``, prefix: ``},
{name: `echo music`, country: ``, mbid: `6ebd6966-e78f-448c-bf4e-bed2855e3627`, prefix: ``},
{name: `egg music`, country: ``, mbid: ``, prefix: `EGG`},
{name: `elbroar`, country: ``, mbid: ``, prefix: ``},
{name: `electronic dance series`, country: ``, mbid: ``, prefix: ``},
{name: `elekt music`, country: ``, mbid: ``, prefix: ``},
{name: `elephant`, country: ``, mbid: `2676fb13-4a6e-4c92-aed1-b8070fc4ae26`, prefix: ``},
{name: `elias music library`, country: ``, mbid: ``, prefix: ``},
{name: `emh classical`, country: ``, mbid: `7394a6ed-ac70-49ef-8ef0-0237f2aa49e2`, prefix: ``},
{name: `encore merci`, country: `FR`, mbid: `07486ab5-d43e-4b29-89b2-c32fb8200fec`, prefix: `EM`},
{name: `end of silence`, country: ``, mbid: ``, prefix: ``},
{name: `enginuity music`, country: `US`, mbid: ``, prefix: `ENG`},
{name: `enterprises sonor`, country: ``, mbid: ``, prefix: ``},
{name: `epic`, country: ``, mbid: `c0f23fba-33e9-4726-a4df-a4ba5ec9616a`, prefix: `EPC`},
{name: `epic north`, country: ``, mbid: ``, prefix: ``},
{name: `epic score`, country: ``, mbid: `c0f23fba-33e9-4726-a4df-a4ba5ec9616a`, prefix: `ES`},
{name: `essential elements`, country: ``, mbid: `2421667d-f48d-4ca9-9ce6-a9045c298311`, prefix: ``},
{name: `evolution media music`, country: ``, mbid: ``, prefix: ``},
{name: `evolving sound`, country: ``, mbid: ``, prefix: `EVS`},
{name: `exclusive artist`, country: ``, mbid: ``, prefix: ``},
{name: `exotic worlds`, country: ``, mbid: ``, prefix: ``},
{name: `extreme easy listening`, country: `GB`, mbid: ``, prefix: `XEL`},
{name: `extreme twisted`, country: `GB`, mbid: ``, prefix: `XTW`},
{name: `eyeballs & eardrums`, country: ``, mbid: ``, prefix: `E&E`},
{name: `fantasy classical collection`, country: ``, mbid: ``, prefix: `CLXY`},
{name: `fantasy documentary series`, country: ``, mbid: ``, prefix: `IDOCS`},
{name: `fantasy easy listening`, country: ``, mbid: ``, prefix: `EZLY`},
{name: `fantasy film series`, country: ``, mbid: ``, prefix: `FEXY`},
{name: `fantasy music`, country: ``, mbid: `3350a31e-c29c-48db-bcca-606842a15856`, prefix: `SEXY`},
{name: `felt archives`, country: ``, mbid: ``, prefix: `FML ARC`},
{name: `felt christmas`, country: ``, mbid: ``, prefix: `FML CH`},
{name: `felt classical masters`, country: ``, mbid: ``, prefix: `FML CM`},
{name: `felt contemporary`, country: ``, mbid: ``, prefix: `FML FC`},
{name: `felt cuckooland`, country: ``, mbid: ``, prefix: `FML CK`},
{name: `felt off to battle`, country: ``, mbid: ``, prefix: `FML OTB`},
{name: `felt orchestral & score`, country: ``, mbid: ``, prefix: `FML OS`},
{name: `felt sound circle`, country: ``, mbid: ``, prefix: `FML SC`},
{name: `felt soundworks`, country: ``, mbid: ``, prefix: `FML SND`},
{name: `felt themes`, country: ``, mbid: ``, prefix: `FML TH`},
{name: `felt trailer`, country: ``, mbid: ``, prefix: `FML TR`},
{name: `felt vintage`, country: ``, mbid: ``, prefix: `FML VN`},
{name: `felt world`, country: ``, mbid: ``, prefix: `FML WR`},
{name: `figure and groove`, country: ``, mbid: ``, prefix: ``},
{name: `fired earth music`, country: ``, mbid: `2930b37e-8d45-4398-ab76-36528bcc2fc3`, prefix: ``},
{name: `flashpoint`, country: ``, mbid: ``, prefix: ``},
{name: `flava of the month`, country: ``, mbid: `cbaad7de-91ee-473b-91c5-af328f553fd5`, prefix: `FLAVA`},
{name: `float music`, country: ``, mbid: ``, prefix: `FL`},
{name: `floor 6`, country: ``, mbid: ``, prefix: ``},
{name: `fm records`, country: ``, mbid: ``, prefix: ``},
{name: `fontana classic collection`, country: ``, mbid: `f0cb607a-76cd-4c0c-85ad-47376f454a3e`, prefix: ``},
{name: `fontana music library classical collection`, country: ``, mbid: ``, prefix: ``},
{name: `fontana music library`, country: ``, mbid: ``, prefix: ``},
{name: `fontana music library virtual series`, country: ``, mbid: ``, prefix: ``},
{name: `forza sound design`, country: ``, mbid: ``, prefix: ``},
{name: `foxhole records`, country: ``, mbid: ``, prefix: `FOX`},
{name: `fpmmusic`, country: ``, mbid: ``, prefix: ``},
{name: `frameworks music`, country: ``, mbid: `d5c0bf9b-3cfe-4911-baad-5f88f70b54db`, prefix: ``},
{name: `fujit music`, country: ``, mbid: ``, prefix: ``},
{name: `full clip music`, country: ``, mbid: ``, prefix: ``},
{name: `full tilt`, country: ``, mbid: `8522b9b5-cb75-402e-ad39-eecda8d2c914`, prefix: ``},
{name: `future pop`, country: ``, mbid: ``, prefix: `FUP`},
{name: `gargantuan creative`, country: ``, mbid: ``, prefix: ``},
{name: `gargantuan music`, country: ``, mbid: ``, prefix: ``},
{name: `gerhard daum music edition`, country: ``, mbid: `f04a0cc2-1257-4af8-89bd-860d62c6b948`, prefix: ``},
{name: `global graffiti`, country: `US`, mbid: ``, prefix: `GGM`},
{name: `glory, oath, and blood`, country: ``, mbid: `2766b4c8-0968-4ac4-ad93-55fefacf4012`, prefix: ``},
{name: `gold series`, country: ``, mbid: ``, prefix: ``},
{name: `gore & audio`, country: `GB`, mbid: ``, prefix: `GAA`},
{name: `gothic hybrid`, country: ``, mbid: ``, prefix: `GHY`},
{name: `gothic storm`, country: ``, mbid: `fbd30909-70f6-4d53-861a-75016740cf06`, prefix: `GOTHIC`},
{name: `gothic storm music`, country: ``, mbid: `fbd30909-70f6-4d53-861a-75016740cf06`, prefix: ``},
{name: `gothic storm's toolworks`, country: ``, mbid: ``, prefix: `GTW`},
{name: `grandmaster`, country: `GB`, mbid: `75c4abbb-670d-4320-805f-7617eb729697`, prefix: `XGM`},
{name: `graphic sound design`, country: ``, mbid: `a3b20f57-3c97-419e-a081-55ff80a8cf09`, prefix: ``},
{name: `gravity`, country: ``, mbid: `f4bad8c4-f2d9-4161-8ec1-607ae4fbf8b3`, prefix: ``},
{name: `green tea label`, country: ``, mbid: ``, prefix: ``},
{name: `green zebra music`, country: ``, mbid: ``, prefix: ``},
{name: `groove addicts`, country: ``, mbid: `3d385d6c-c6d5-4cb4-b3a7-405b23a26cd6`, prefix: ``},
{name: `gsound`, country: ``, mbid: ``, prefix: `GSOUND`},
{name: `gum collections`, country: `FR`, mbid: `47967ba5-046f-4249-947a-ce5ab93f1cca`, prefix: `GUM`},
{name: `gum motion tracks`, country: `FR`, mbid: ``, prefix: `GMT`},
{name: `h2u`, country: ``, mbid: ``, prefix: ``},
{name: `happy records`, country: ``, mbid: `03c8fc38-c46f-418b-9da7-3ba47de157b7`, prefix: `HR`},
{name: `hard`, country: ``, mbid: ``, prefix: ``},
{name: `harvest media`, country: ``, mbid: ``, prefix: ``},
{name: `hdmn prime`, country: ``, mbid: ``, prefix: ``},
{name: `heavy melody trailers`, country: ``, mbid: ``, prefix: `HMT`},
{name: `heavy promos`, country: ``, mbid: `351ea7da-0ed9-469e-b4cb-7704725d3ab4`, prefix: `HP`},
{name: `heavy promos sound design`, country: ``, mbid: ``, prefix: `HPFX`},
{name: `hella good records`, country: ``, mbid: `cd45e243-650b-4182-a77d-5b2b436131c8`, prefix: ``},
{name: `hella good records mix`, country: ``, mbid: `cd45e243-650b-4182-a77d-5b2b436131c8`, prefix: ``},
{name: `hen's teeth music`, country: ``, mbid: `d794fced-59b4-482e-891b-534470c422a4`, prefix: `HTM`},
{name: `here tomorrow music`, country: ``, mbid: ``, prefix: ``},
{name: `highlight scene`, country: ``, mbid: ``, prefix: ``},
{name: `hillsong`, country: ``, mbid: ``, prefix: ``},
{name: `homegrown`, country: ``, mbid: ``, prefix: `HOME`},
{name: `hum tracks`, country: ``, mbid: ``, prefix: ``},
{name: `hypekit`, country: ``, mbid: ``, prefix: `HK`},
{name: `hype music`, country: `GB`, mbid: ``, prefix: `HYP`},
{name: `hyperlocal`, country: `US`, mbid: ``, prefix: `HL`},
{name: `hypersonic`, country: ``, mbid: ``, prefix: ``},
{name: `ieun music`, country: ``, mbid: ``, prefix: ``},
{name: `ignite`, country: ``, mbid: `19c79b97-5646-40bf-bb4a-96b4851f5d67`, prefix: ``},
{name: `iiad if it aint dutch`, country: ``, mbid: ``, prefix: ``},
{name: `iliad - beach road music`, country: `US`, mbid: ``, prefix: `ILD`},
{name: `image edge library`, country: ``, mbid: ``, prefix: ``},
{name: `image music library`, country: ``, mbid: `27820313-81d4-4507-9731-bc8024fa95f9`, prefix: ``},
{name: `image music: the classic series`, country: ``, mbid: `27820313-81d4-4507-9731-bc8024fa95f9`, prefix: ``},
{name: `image promos`, country: ``, mbid: ``, prefix: ``},
{name: `imagine music`, country: ``, mbid: ``, prefix: ``},
{name: `i miss you records`, country: ``, mbid: ``, prefix: ``},
{name: `immediate music`, country: ``, mbid: `53574995-44bf-4656-a70f-25e040b4ac87`, prefix: `IMX`},
{name: `immortal music`, country: ``, mbid: ``, prefix: `IMM`},
{name: `i’m not a machine music`, country: ``, mbid: ``, prefix: `INAMM`},
{name: `impact trailer music`, country: `US`, mbid: ``, prefix: `ITMCD`},
{name: `impressive minds`, country: ``, mbid: ``, prefix: ``},
{name: `impulsion`, country: `CA`, mbid: ``, prefix: `IMP`},
{name: `indie production music`, country: ``, mbid: ``, prefix: ``},
{name: `indiesonics`, country: ``, mbid: ``, prefix: `IND`},
{name: `indiesonics library`, country: ``, mbid: ``, prefix: ``},
{name: `infini`, country: ``, mbid: `2924afdc-d02f-4376-a584-cc0a11310cba`, prefix: ``},
{name: `in pictures`, country: ``, mbid: ``, prefix: `INPIC`},
{name: `in-spired`, country: ``, mbid: `4ac19702-222c-4623-be20-5722563b584f`, prefix: `IPM`},
{name: `inspired production music`, country: ``, mbid: `4ac19702-222c-4623-be20-5722563b584f`, prefix: ``},
{name: `intah`, country: `US`, mbid: ``, prefix: `INTAH`},
{name: `intermede`, country: ``, mbid: ``, prefix: `INT`},
{name: `intermede music`, country: ``, mbid: ``, prefix: ``},
{name: `intersound`, country: ``, mbid: `be0cffb1-b3f2-465f-8753-1d27c1a10caf`, prefix: `ISCD`},
{name: `intervox`, country: ``, mbid: `5c2d7816-147b-4f88-8338-9c7cf1cd0936`, prefix: `IVOX`},
{name: `intervox production music`, country: ``, mbid: `5c2d7816-147b-4f88-8338-9c7cf1cd0936`, prefix: ``},
{name: `in the groove`, country: ``, mbid: `a7c8ba97-c602-4671-9fa9-9ec6b8918054`, prefix: `ITG`},
{name: `invisible world music`, country: ``, mbid: `ca985a33-f836-409f-a213-5c7b20c3ee81`, prefix: ``},
{name: `jamm`, country: ``, mbid: ``, prefix: ``},
{name: `john andrew schreiner`, country: ``, mbid: ``, prefix: ``},
{name: `john fulford music`, country: ``, mbid: ``, prefix: ``},
{name: `jolt trailer music`, country: ``, mbid: ``, prefix: `JTM`},
{name: `jsak`, country: `JP`, mbid: ``, prefix: `JSAK`},
{name: `justement music`, country: ``, mbid: `331ca2d1-337a-4c33-acac-8eb0438063bf`, prefix: `JUST`},
{name: `jw media music`, country: ``, mbid: `fac7e148-ef7a-4127-b4c0-6f6744063dc4`, prefix: `JW`},
{name: `jw vault collection`, country: ``, mbid: ``, prefix: `JWV`},
{name: `king caffeine music`, country: ``, mbid: ``, prefix: ``},
{name: `kingdom 2`, country: ``, mbid: ``, prefix: `KING`},
{name: `king size`, country: ``, mbid: `2b087850-983f-4626-a976-336eba009111`, prefix: ``},
{name: `klanglobby`, country: ``, mbid: ``, prefix: `KL`},
{name: `konic records publishing`, country: ``, mbid: ``, prefix: ``},
{name: `konsonant music`, country: ``, mbid: ``, prefix: ``},
{name: `kool kat`, country: ``, mbid: `ffee822b-3112-4382-9e0c-f64f57326414`, prefix: `KAT`},
{name: `kool music`, country: ``, mbid: ``, prefix: ``},
{name: `kosinus archives`, country: `FR`, mbid: ``, prefix: `KOA`},
{name: `kosinus arts`, country: `FR`, mbid: `349e2e06-6b9d-4f79-bb15-c9320a59798c`, prefix: `KAR`},
{name: `kosinus classical`, country: `FR`, mbid: ``, prefix: `KCL`},
{name: `kosinus`, country: `FR`, mbid: `4dc92454-5ea6-468b-83ec-c925efd930d4`, prefix: `KOS`},
{name: `kosinus magazine`, country: `FR`, mbid: `d3fc0c98-f9f6-4b9e-bce1-74ce44d76a90`, prefix: `KOM`},
{name: `kosinus on line`, country: `FR`, mbid: `4ceff2bb-1025-46de-bf89-2008fb41b571`, prefix: `KOL`},
{name: `koto`, country: `JP`, mbid: ``, prefix: `KOTO`},
{name: `kurt bestor music`, country: ``, mbid: ``, prefix: ``},
{name: `kxc`, country: ``, mbid: ``, prefix: ``},
{name: `kyle newmaster`, country: ``, mbid: ``, prefix: ``},
{name: `lab rat recordings`, country: `GB`, mbid: ``, prefix: `XLR`},
{name: `l.a. edition`, country: ``, mbid: ``, prefix: ``},
{name: `law & audio`, country: `GB`, mbid: ``, prefix: `LAA`},
{name: `lemoncake music`, country: ``, mbid: ``, prefix: ``},
{name: `lesterbeat records`, country: ``, mbid: ``, prefix: ``},
{name: `library of the human soul`, country: ``, mbid: ``, prefix: `LHS`},
{name: `liftmusic`, country: ``, mbid: `b924fe83-f68a-4882-add2-21e436d70892`, prefix: `LIFT`},
{name: `liftmusic factual`, country: ``, mbid: ``, prefix: `FACT`},
{name: `liftmusic wildcards`, country: ``, mbid: `0c54ff07-6977-4854-bad0-d795775fa13c`, prefix: `WILD`},
{name: `lmntl records`, country: ``, mbid: ``, prefix: `LMTL`},
{name: `lovely music`, country: ``, mbid: ``, prefix: `LVM`},
{name: `lovely music library`, country: ``, mbid: ``, prefix: ``},
{name: `lucas cantor library`, country: ``, mbid: ``, prefix: ``},
{name: `made`, country: `GB`, mbid: ``, prefix: `MDE`},
{name: `magazine records`, country: `FR`, mbid: `12787e79-fc40-462e-8929-5dd6a980468c`, prefix: `MR`},
{name: `magnetic records`, country: `FR`, mbid: `12787e79-fc40-462e-8929-5dd6a980468c`, prefix: `MAG`},
{name: `marnie`, country: ``, mbid: ``, prefix: ``},
{name: `marquee music`, country: `US`, mbid: `23b61da0-5510-4616-b6fe-5224d34ac3ac`, prefix: `MQ`},
{name: `massive bass`, country: ``, mbid: ``, prefix: ``},
{name: `mathambo music`, country: ``, mbid: `fed4f2dc-2360-4103-a6cc-bf91ed989a49`, prefix: ``},
{name: `mediatracks`, country: ``, mbid: `6dc40b74-bb2a-4277-9786-93101a11db0a`, prefix: ``},
{name: `megatrax`, country: `US`, mbid: `a82773f8-8f6d-483f-9b2a-3fdc0d0d4418`, prefix: `MX`},
{name: `merge music`, country: ``, mbid: ``, prefix: ``},
{name: `methodic doubt materials`, country: ``, mbid: ``, prefix: ``},
{name: `metro`, country: ``, mbid: `c7ff6ed0-58dc-4bb5-bdfb-5dcd69396952`, prefix: ``},
{name: `mexican music library`, country: ``, mbid: ``, prefix: `MML`},
{name: `midcoast music artist songs`, country: ``, mbid: ``, prefix: ``},
{name: `midcoast music wired`, country: ``, mbid: ``, prefix: ``},
{name: `mindbenders`, country: ``, mbid: `4040ba54-4753-4140-ac49-e71e12531104`, prefix: ``},
{name: `minds and music`, country: ``, mbid: `9d791422-9236-4776-94cb-48f908f651b5`, prefix: `MAM`},
{name: `minimal`, country: ``, mbid: `1da94f57-1577-4c5c-82e4-593678b16a87`, prefix: ``},
{name: `minimalism`, country: ``, mbid: ``, prefix: ``},
{name: `minimal tv`, country: ``, mbid: ``, prefix: ``},
{name: `minim`, country: ``, mbid: ``, prefix: `MNM`},
{name: `misszik`, country: ``, mbid: ``, prefix: `MISSZIK`},
{name: `mixtape`, country: `GB`, mbid: `a73e1b87-96f5-4e07-ae66-e69e4f57907a`, prefix: `XMT`},
{name: `mode production music ltd`, country: ``, mbid: ``, prefix: ``},
{name: `modus operandi`, country: ``, mbid: `fce6b313-d3ba-43a2-af77-630d55683c2d`, prefix: `MOPM`},
{name: `montage music`, country: ``, mbid: ``, prefix: `MMX`},
{name: `montmorency records`, country: ``, mbid: `92c2d46a-71d9-4bf7-b390-d4b5c5a6b8b1`, prefix: `MYR`},
{name: `motion focus music`, country: ``, mbid: ``, prefix: ``},
{name: `motus music`, country: ``, mbid: ``, prefix: ``},
{name: `move music`, country: ``, mbid: ``, prefix: ``},
{name: `muse`, country: ``, mbid: ``, prefix: `MUSE`},
{name: `musica britannica`, country: ``, mbid: ``, prefix: `ESL-MB`},
{name: `musical concepts`, country: `US`, mbid: ``, prefix: `MCCD`},
{name: `music beyond`, country: ``, mbid: ``, prefix: `BYND`},
{name: `musicbox classics`, country: ``, mbid: ``, prefix: `MBC`},
{name: `musicbox`, country: ``, mbid: `5c11e028-c078-4b2f-837d-249fb9acb281`, prefix: `MB`},
{name: `music candy`, country: ``, mbid: ``, prefix: ``},
{name: `music for productions`, country: `CA`, mbid: ``, prefix: `MFP`},
{name: `music for sport`, country: ``, mbid: `292e2f2c-c8f7-431e-bcf9-c132f7d49cdc`, prefix: ``},
{name: `music gallery`, country: `FR`, mbid: `016ec2ce-0da8-485e-b77a-14ee7715a1e0`, prefix: `MG`},
{name: `music outside the box`, country: ``, mbid: ``, prefix: ``},
{name: `music shop`, country: `FR`, mbid: `539eb12d-3328-4de0-8e6d-94ccd320c943`, prefix: ``},
{name: `music shop online`, country: `FR`, mbid: ``, prefix: `MSO`},
{name: `music shop tools`, country: `FR`, mbid: `70f78d17-dc81-4484-a650-bcd7cda3b156`, prefix: `MT`},
{name: `music shop zen`, country: `FR`, mbid: `9a12fd69-2845-4aa9-b893-0d70d4a65761`, prefix: `ZEN`},
{name: `musique & music`, country: ``, mbid: `af3a2ccd-b66e-4d9d-b33d-394c8319a93f`, prefix: `ZIK`},
{name: `must save jane`, country: ``, mbid: ``, prefix: `MSJ`},
{name: `muzikotek`, country: ``, mbid: `74090679-1404-4e61-80e4-d02a1c285e1d`, prefix: `MUZ`},
{name: `muzronic trailer music`, country: ``, mbid: ``, prefix: ``},
{name: `naked music`, country: ``, mbid: ``, prefix: ``},
{name: `nelvana`, country: ``, mbid: ``, prefix: `NLV`},
{name: `new west studios scoring collection`, country: ``, mbid: ``, prefix: `NWS`},
{name: `nine lives music`, country: ``, mbid: ``, prefix: ``},
{name: `ninja tracks`, country: ``, mbid: ``, prefix: ``},
{name: `ninja tune production music`, country: ``, mbid: ``, prefix: `NTPM`},
{name: `non stop premiere`, country: ``, mbid: `a3efb8bc-c01d-4a44-a6eb-a2f5916b1be1`, prefix: ``},
{name: `non stop producer series`, country: ``, mbid: `6e8a3e48-1137-4539-9de2-bee9a5773a24`, prefix: ``},
{name: `no sheet music`, country: ``, mbid: ``, prefix: ``},
{name: `nova nota`, country: ``, mbid: `470d76d3-12f4-4e28-bbe3-02a911c05be6`, prefix: `NVN`},
{name: `n-trax`, country: ``, mbid: ``, prefix: ``},
{name: `octopus`, country: `IT`, mbid: ``, prefix: `OTP`},
{name: `octopus records`, country: ``, mbid: ``, prefix: ``},
{name: `off the shelf music`, country: ``, mbid: `d22f6596-ca69-4b15-b6d3-a65fc4a60209`, prefix: ``},
{name: `omni`, country: ``, mbid: ``, prefix: ``},
{name: `opening line music group`, country: ``, mbid: ``, prefix: ``},
{name: `open sound music`, country: ``, mbid: ``, prefix: ``},
{name: `open sound vintage`, country: ``, mbid: ``, prefix: ``},
{name: `opus1`, country: `US`, mbid: `e5893830-f9f5-41ca-ae9a-eb69f990afb5`, prefix: `OPUS`},
{name: `organic spark`, country: ``, mbid: `1223b8f8-b255-404a-a23b-7a3a7d1710da`, prefix: `OSPK`},
{name: `ours music`, country: `FR`, mbid: ``, prefix: `OML`},
{name: `pa74 music`, country: ``, mbid: ``, prefix: ``},
{name: `parigo`, country: `FR`, mbid: `9975785f-d31d-4031-944f-0527d0a2649f`, prefix: `PGO`},
{name: `parry classical`, country: ``, mbid: `61c048b7-3e84-4d46-b9f7-18b88855630a`, prefix: `PMC`},
{name: `parry music classical`, country: ``, mbid: `61c048b7-3e84-4d46-b9f7-18b88855630a`, prefix: ``},
{name: `parry music`, country: ``, mbid: `f5e158cc-8ef6-4b7c-aee4-9b72bd791015`, prefix: ``},
{name: `parry music library`, country: ``, mbid: `f5e158cc-8ef6-4b7c-aee4-9b72bd791015`, prefix: `PML`},
{name: `passport`, country: `GB`, mbid: `e6f0f3a1-502f-4a2e-bd18-5721319676e3`, prefix: `XPS`},
{name: `pedigree cuts`, country: ``, mbid: `52d7fc99-6cfd-4738-98ad-b722248a83df`, prefix: `PED`},
{name: `pennybank tunes`, country: `FR`, mbid: `09166de7-dfd1-4ff1-aa81-801a708a9c13`, prefix: `PNBT`},
{name: `pennybank tunes profiles`, country: `FR`, mbid: `09166de7-dfd1-4ff1-aa81-801a708a9c13`, prefix: `PNBP`},
{name: `perfect pitch`, country: ``, mbid: `deb54842-8156-4b24-bed2-b7cd3a4cd2af`, prefix: ``},
{name: `perfect time publishing`, country: ``, mbid: ``, prefix: ``},
{name: `piano for film`, country: ``, mbid: `a3f3fcf4-5d16-4330-bc1d-f7932843bfff`, prefix: ``},
{name: `picture puncture`, country: ``, mbid: ``, prefix: `PICX`},
{name: `pilo and smith`, country: ``, mbid: ``, prefix: ``},
{name: `pitchhammer`, country: ``, mbid: ``, prefix: `PTCH`},
{name: `pitch hammer music`, country: ``, mbid: ``, prefix: ``},
{name: `plan 8 music`, country: ``, mbid: `fd27a212-8246-4186-a35e-6a5b4ff33dc2`, prefix: ``},
{name: `playground hollywood`, country: ``, mbid: `6b7a2131-3d71-4e90-b2ab-a61ec215c8aa`, prefix: `PGH`},
{name: `playlist`, country: ``, mbid: ``, prefix: `PLAY`},
{name: `pmol`, country: ``, mbid: ``, prefix: ``},
{name: `poke`, country: ``, mbid: ``, prefix: ``},
{name: `poke music`, country: ``, mbid: `e9f6d244-3973-49b1-8e1e-bd0c307f8e1b`, prefix: `POKE`},
{name: `popcorn music`, country: ``, mbid: ``, prefix: `POPC`},
{name: `popvirus music`, country: ``, mbid: ``, prefix: ``},
{name: `postcards from the world`, country: ``, mbid: ``, prefix: ``},
{name: `post production music`, country: ``, mbid: `d2ce9db0-ae06-4643-b23b-9087b90b3aff`, prefix: `PPM`},
{name: `pp music`, country: ``, mbid: `56ea4f9c-11a1-4d14-ab37-894fd6aebf37`, prefix: `PP`},
{name: `primrose classical`, country: ``, mbid: `270c778d-96e7-43ad-853e-6657629e1261`, prefix: ``},
{name: `primrose classical white label`, country: ``, mbid: ``, prefix: ``},
{name: `primrose`, country: `IT`, mbid: `110575f3-7bc6-4723-9bd2-bb021a24a233`, prefix: `PRCD`},
{name: `primrose music`, country: ``, mbid: `110575f3-7bc6-4723-9bd2-bb021a24a233`, prefix: ``},
{name: `production music online`, country: ``, mbid: `d8889e78-f436-45f6-b8a0-8dce30c1e2cc`, prefix: `PMOL`},
{name: `promo accelerator`, country: ``, mbid: `9a901a50-95b4-498d-bc75-8ef3d8d540b5`, prefix: ``},
{name: `promobox`, country: ``, mbid: `86f6efc7-8378-49eb-a7d7-2ac221da59fc`, prefix: `PB`},
{name: `pro viva`, country: ``, mbid: ``, prefix: `ISPV`},
{name: `prowerks`, country: ``, mbid: ``, prefix: ``},
{name: `pure music`, country: `US`, mbid: ``, prefix: `PURM`},
{name: `push pop`, country: ``, mbid: ``, prefix: ``},
{name: `püsh pop`, country: ``, mbid: ``, prefix: `PPOP`},
{name: `q-factory by robert etoll`, country: ``, mbid: `dc3a51a3-685b-4e5a-a454-61e7debf0d9d`, prefix: ``},
{name: `q-factory`, country: ``, mbid: `dc3a51a3-685b-4e5a-a454-61e7debf0d9d`, prefix: `REP`},
{name: `q-series`, country: `GB`, mbid: `812eb9a1-e461-430c-b203-019b3698e7ed`, prefix: `QCD`},
{name: `quest`, country: `GB`, mbid: ``, prefix: `QWP`},
{name: `ravenwood music`, country: ``, mbid: `4dea27c9-3a78-40e1-8b06-09554a5b6ca6`, prefix: ``},
{name: `ready made production`, country: `FR`, mbid: ``, prefix: `RMP`},
{name: `reality check`, country: `GB`, mbid: ``, prefix: `XRC`},
{name: `really slow motion music`, country: ``, mbid: ``, prefix: ``},
{name: `records room music`, country: ``, mbid: ``, prefix: ``},
{name: `redcola`, country: `US`, mbid: `27ffa24e-964c-49c9-b6ed-fb92e328c8cf`, prefix: `RC`},
{name: `redcola music library`, country: ``, mbid: `27ffa24e-964c-49c9-b6ed-fb92e328c8cf`, prefix: ``},
{name: `red igloo music`, country: ``, mbid: ``, prefix: ``},
{name: `refuel music`, country: ``, mbid: `c5966a8e-2b6f-41e6-9162-682b818a0914`, prefix: ``},
{name: `resolution music collection`, country: ``, mbid: ``, prefix: ``},
{name: `revolucion`, country: ``, mbid: `49e7c1b9-b614-4a20-b469-02875a0b616a`, prefix: ``},
{name: `revolution - international`, country: ``, mbid: `49e7c1b9-b614-4a20-b469-02875a0b616a`, prefix: ``},
{name: `ridgeline music`, country: ``, mbid: `3e41fde0-e42c-478d-9c19-7ab88a53b29c`, prefix: ``},
{name: `rightsify`, country: ``, mbid: ``, prefix: ``},
{name: `ring musik`, country: ``, mbid: ``, prefix: ``},
{name: `roba series`, country: ``, mbid: ``, prefix: ``},
{name: `rogue souls`, country: ``, mbid: ``, prefix: `ROG`},
{name: `runaway records`, country: ``, mbid: ``, prefix: ``},
{name: `sak`, country: `JP`, mbid: ``, prefix: `SAK`},
{name: `sauce music`, country: ``, mbid: `3ff42e9b-d203-4ae9-92db-5aa6fcec41a0`, prefix: `SM`},
{name: `scaremeister`, country: ``, mbid: `2e1b4d42-9f5b-405f-bdff-14129e851357`, prefix: ``},
{name: `scorched score`, country: ``, mbid: ``, prefix: `SCR`},
{name: `scorched score music`, country: ``, mbid: ``, prefix: ``},
{name: `score`, country: ``, mbid: `fc6a2eb0-5479-403c-ae39-03da379496ad`, prefix: `SCORE`},
{name: `scoreganics`, country: `GB`, mbid: `3b4cd53e-d653-4f62-8895-6f20de276e53`, prefix: `SCS`},
{name: `score production music`, country: ``, mbid: `fc6a2eb0-5479-403c-ae39-03da379496ad`, prefix: ``},
{name: `scoring stage`, country: ``, mbid: `b9916509-a3f0-443f-a55e-d0be3cb9fde3`, prefix: ``},
{name: `scout music`, country: ``, mbid: ``, prefix: ``},
{name: `selectracks`, country: ``, mbid: ``, prefix: ``},
{name: `selectracks instrumental catalog`, country: ``, mbid: ``, prefix: `ST`},
{name: `selectracks instrumental`, country: ``, mbid: ``, prefix: `ST`},
{name: `selectracks song catalog`, country: ``, mbid: ``, prefix: `SC`},
{name: `sensacion`, country: `US`, mbid: `922eb96d-8276-4472-a1d6-4bdc059b12c6`, prefix: `SN`},
{name: `sensory overload music`, country: ``, mbid: ``, prefix: ``},
{name: `sheerline records`, country: ``, mbid: ``, prefix: ``},
{name: `shock files`, country: `US`, mbid: ``, prefix: `SKF`},
{name: `shout! music`, country: ``, mbid: ``, prefix: ``},
{name: `shout! music publishing`, country: ``, mbid: ``, prefix: ``},
{name: `sick muse music`, country: ``, mbid: ``, prefix: `SMM `},
{name: `silent methods`, country: ``, mbid: `f4de1e72-5785-4e1b-a4bd-e2178907433f`, prefix: ``},
{name: `silver screen`, country: ``, mbid: ``, prefix: `SIL`},
{name: `soho archive`, country: ``, mbid: ``, prefix: ``},
{name: `soho`, country: ``, mbid: ``, prefix: ``},
{name: `somos`, country: ``, mbid: ``, prefix: ``},
{name: `songcraft`, country: ``, mbid: ``, prefix: `SONG`},
{name: `song junkies`, country: ``, mbid: ``, prefix: `SJM`},
{name: `songs to your eyes music`, country: ``, mbid: ``, prefix: `STYE`},
{name: `song zu`, country: ``, mbid: ``, prefix: `SZ`},
{name: `sonia classics`, country: ``, mbid: ``, prefix: `SONIA`},
{name: `sonic artefact`, country: ``, mbid: ``, prefix: `SA`},
{name: `sonic artifact`, country: ``, mbid: ``, prefix: `SA`},
{name: `sonic quiver`, country: ``, mbid: `f1140a2c-dc02-4a58-84d4-b00b5a827944`, prefix: `SQ`},
{name: `sonic symphony`, country: `US`, mbid: `78d8439b-8ca5-4e95-bc94-ecdd71aa0779`, prefix: `SSY`},
{name: `sonictremor`, country: ``, mbid: ``, prefix: ``},
{name: `sonoton authentic series`, country: ``, mbid: `140a26d4-6632-41cb-b0af-d3a061242faa`, prefix: `SAS`},
{name: `sonoton classical`, country: ``, mbid: `4d5e4398-c966-49d8-a2f0-300794e5cbfe`, prefix: `SCDC`},
{name: `sonoton`, country: ``, mbid: `30864815-1104-466d-8900-5a8baaa2203b`, prefix: `SCD`},
{name: `sonoton rockshop`, country: ``, mbid: ``, prefix: `SCD RCK`},
{name: `sonoton trailer tracks`, country: ``, mbid: `3a3c068f-854e-4a04-b8d7-d11aa9a80c01`, prefix: `STT`},
{name: `sonoton trailer tracks virtual`, country: ``, mbid: `695a9672-7937-4da1-83ef-809678bb1209`, prefix: `STTV`},
{name: `sonoton vanguard`, country: ``, mbid: ``, prefix: `SCDV`},
{name: `soulstudio7`, country: `US`, mbid: ``, prefix: `SSS`},
{name: `sound adventures`, country: `CH`, mbid: `9fabdd31-32af-41b8-a0ad-f790fb5b1d3e`, prefix: `SAV`},
{name: `sound for prod`, country: ``, mbid: ``, prefix: ``},
{name: `soundiva classical`, country: ``, mbid: ``, prefix: ``},
{name: `soundiva`, country: ``, mbid: ``, prefix: ``},
{name: `sound music album`, country: ``, mbid: `3db99f45-3675-48e6-a6ec-36dece2ec1de`, prefix: `SMA`},
{name: `soundtrackboutique`, country: ``, mbid: ``, prefix: ``},
{name: `soundtrax music`, country: ``, mbid: `574f51d0-d5ad-4f6d-81bb-8fc3a7e334da`, prefix: ``},
{name: `soundtrax music jingle box music`, country: ``, mbid: ``, prefix: ``},
{name: `source in sync`, country: `US`, mbid: `102f1347-8c9e-42e3-a7f8-10ed264cfdb6`, prefix: `SIS`},
{name: `source in sync music`, country: ``, mbid: `102f1347-8c9e-42e3-a7f8-10ed264cfdb6`, prefix: ``},
{name: `spain is music`, country: ``, mbid: `ca3a8b06-8b50-411b-807c-53ab7b93bfdc`, prefix: ``},
{name: `sparse music`, country: `DE`, mbid: ``, prefix: `SPRS`},
{name: `special requests`, country: ``, mbid: ``, prefix: ``},
{name: `spice vocal library`, country: ``, mbid: ``, prefix: ``},
{name: `spider cues`, country: `US`, mbid: `688d3f7a-5347-4c81-97e0-b30a080f7381`, prefix: `SQE`},
{name: `spintrest`, country: `GB`, mbid: ``, prefix: `SPN`},
{name: `spot society`, country: ``, mbid: ``, prefix: ``},
{name: `sprint edge`, country: ``, mbid: ``, prefix: ``},
{name: `sprint music library`, country: ``, mbid: `64d22e5a-d4fa-4adc-80f1-9eba053c8414`, prefix: ``},
{name: `stampede`, country: `GB`, mbid: `48398802-88f0-439f-af08-ab941b1f28ab`, prefix: `XST`},
{name: `standard music`, country: ``, mbid: `ce998234-fce7-4e3c-b569-c65e359444c2`, prefix: `ESL`},
{name: `standard music library`, country: ``, mbid: `ce998234-fce7-4e3c-b569-c65e359444c2`, prefix: ``},
{name: `stephen arnold music`, country: ``, mbid: ``, prefix: ``},
{name: `stereoroyal`, country: ``, mbid: `87b39159-15b7-4ea1-a04d-3076e202f92c`, prefix: `STR`},
{name: `stereoscopic`, country: ``, mbid: ``, prefix: `SCOP`},
{name: `steve schiltz music`, country: ``, mbid: ``, prefix: ``},
{name: `stock music`, country: ``, mbid: `3ad6e6fe-5e23-4e6f-b218-065c9b3d588f`, prefix: ``},
{name: `straight up! world`, country: ``, mbid: ``, prefix: ``},
{name: `strange fruit commercial breaks`, country: ``, mbid: ``, prefix: ``},
{name: `strange fruit`, country: ``, mbid: ``, prefix: ``},
{name: `strip sounds`, country: ``, mbid: `4784a6bb-716e-4395-8263-ff92d70eb5e8`, prefix: `STRP`},
{name: `studio g`, country: ``, mbid: `6ad9a8bd-fed9-4b4b-833f-50657bcaff97`, prefix: `SG`},
{name: `stye classical`, country: ``, mbid: ``, prefix: ``},
{name: `sunstone recordings`, country: ``, mbid: ``, prefix: `SUN`},
{name: `superfly audio`, country: ``, mbid: `013eea1f-bd3c-460e-99ca-aaeb153a5ffd`, prefix: `SFLY`},
{name: `superpitch artist series`, country: ``, mbid: ``, prefix: `SUPIAS`},
{name: `superpitch`, country: ``, mbid: ``, prefix: `SUPI`},
{name: `superpitch drama`, country: ``, mbid: ``, prefix: `SUPIDR`},
{name: `superpitch entertainment`, country: ``, mbid: ``, prefix: `SUPIE`},
{name: `super pop`, country: `GB`, mbid: ``, prefix: `XSP`},
{name: `super rock`, country: `GB`, mbid: ``, prefix: `XSR`},
{name: `super sonic noise`, country: ``, mbid: ``, prefix: ``},
{name: `superstore`, country: ``, mbid: ``, prefix: `SUPER`},
{name: `surefire`, country: ``, mbid: ``, prefix: `SURE`},
{name: `synchro music`, country: ``, mbid: `3d76540b-08bf-4bb1-af4c-96503a096600`, prefix: ``},
{name: `synchronized soundworks production music`, country: ``, mbid: ``, prefix: ``},
{name: `syncstories`, country: ``, mbid: ``, prefix: `STORY`},
{name: `tanzan music`, country: ``, mbid: ``, prefix: ``},
{name: `tape stop music`, country: ``, mbid: ``, prefix: ``},
{name: `tele music classic vault`, country: ``, mbid: ``, prefix: ``},
{name: `tele music`, country: ``, mbid: ``, prefix: ``},
{name: `telesongz`, country: `US`, mbid: ``, prefix: `TLS`},
{name: `teletunez`, country: `US`, mbid: ``, prefix: `TT`},
{name: `that's amore`, country: `IT`, mbid: ``, prefix: `TA`},
{name: `the 13 brotherhood`, country: `GB`, mbid: ``, prefix: `XXL`},
{name: `the artist collection`, country: ``, mbid: ``, prefix: ``},
{name: `the box`, country: ``, mbid: ``, prefix: `TBX`},
{name: `the den`, country: ``, mbid: ``, prefix: `DEN`},
{name: `the devil's cut`, country: `GB`, mbid: ``, prefix: `XDC`},
{name: `the diner music`, country: ``, mbid: ``, prefix: ``},
{name: `the film music of ronald stein`, country: ``, mbid: ``, prefix: `RS`},
{name: `the funky junkies`, country: ``, mbid: `a390061b-5e08-403a-a8b0-193c48d78a2b`, prefix: `TFJ`},
{name: `the moonshine music`, country: `GB`, mbid: ``, prefix: `XXX`},
{name: `the perfect music library`, country: `GB`, mbid: ``, prefix: `TPML`},
{name: `the scene`, country: `US`, mbid: `89cc9b5d-9c89-44ff-a2f6-1eab2919b3d8`, prefix: `TS`},
{name: `the scoring house`, country: ``, mbid: `1ebfd5c5-2d7e-4353-af93-2470e1a5155c`, prefix: ``},
{name: `the scoring house editions`, country: ``, mbid: `1ebfd5c5-2d7e-4353-af93-2470e1a5155c`, prefix: ``},
{name: `the x-files`, country: ``, mbid: ``, prefix: ``},
{name: `the x-motion`, country: ``, mbid: ``, prefix: ``},
{name: `think brazil music`, country: ``, mbid: ``, prefix: ``},
{name: `third rail`, country: ``, mbid: ``, prefix: `IIIR`},
{name: `three ingredients or less`, country: ``, mbid: `4281c5b5-bca9-4f57-a4a1-2300ba12ff74`, prefix: `3ING`},
{name: `tonal injection`, country: `US`, mbid: `90997446-f34b-4858-89d9-c3a22b5a22fa`, prefix: `TI`},
{name: `track distillery`, country: `US`, mbid: ``, prefix: `TD`},
{name: `trailer trash music`, country: ``, mbid: `0ba1b16c-d4c4-4916-9283-d22fc4cab4af`, prefix: ``},
{name: `trax4pro`, country: ``, mbid: ``, prefix: `TX`},
{name: `trede collection`, country: ``, mbid: `aaf76847-4a0d-4dee-86ba-51d033a2600c`, prefix: `TREDE`},
{name: `tree of arts`, country: ``, mbid: ``, prefix: ``},
{name: `tubesounds`, country: ``, mbid: ``, prefix: `TUBE`},
{name: `tv club`, country: ``, mbid: ``, prefix: ``},
{name: `twelvetones art series`, country: ``, mbid: ``, prefix: ``},
{name: `twelvetones`, country: ``, mbid: ``, prefix: ``},
{name: `twelvetones production music`, country: ``, mbid: ``, prefix: ``},
{name: `twisted jukebox`, country: ``, mbid: `fb98bbda-e442-49d0-86fe-abe482251ab9`, prefix: `TJ`},
{name: `two steps from hell`, country: `GB`, mbid: `3b3bd441-5082-421b-9234-a7f48a1ab3b9`, prefix: `XTS`},
{name: `ultimate classix`, country: `GB`, mbid: `49b40560-dc37-4dda-87b0-ad4019df47ce`, prefix: `XCL`},
{name: `ultimate crime & drama`, country: ``, mbid: `3f0bdcc9-fe5b-4572-888f-17439130df3a`, prefix: ``},
{name: `ultraphonic`, country: ``, mbid: `ef107e0a-47cf-47d0-a6fe-1317b9f5fc6b`, prefix: `UPMCD`},
{name: `undercurrents music`, country: ``, mbid: ``, prefix: `UCM`},
{name: `underscore`, country: ``, mbid: `d8a97565-2a02-4ae4-a48b-de1752063b41`, prefix: `UND`},
{name: `updownup`, country: ``, mbid: ``, prefix: ``},
{name: `vadzimu`, country: ``, mbid: ``, prefix: `VAD`},
{name: `valentino`, country: ``, mbid: ``, prefix: `VT`},
{name: `v`, country: ``, mbid: `20d0dd1a-b3e1-4b29-baa5-90d8ba5e7904`, prefix: `VPL`},
{name: `velvet ears`, country: `GB`, mbid: ``, prefix: `VEX`},
{name: `vibey`, country: ``, mbid: `8d8ab661-0e4f-49ff-a164-fb32b0a5a887`, prefix: `VIBEY`},
{name: `vibey underscores`, country: ``, mbid: ``, prefix: `UN`},
{name: `vibrant music`, country: `GB`, mbid: ``, prefix: `VIBE`},
{name: `war & audio`, country: `GB`, mbid: ``, prefix: `WAA`},
{name: `warner chappell music italia`, country: ``, mbid: `802abc00-eba3-4d9f-a583-88af47c03ded`, prefix: `WCMI`},
{name: `west one music`, country: ``, mbid: `320d1d76-d454-4a41-a96b-d3021f766f64`, prefix: `WOM`},
{name: `west one music group`, country: ``, mbid: `320d1d76-d454-4a41-a96b-d3021f766f64`, prefix: `WOM`},
{name: `who did that music`, country: `US`, mbid: `75892da4-7d87-44f4-b502-1e0a60f466e3`, prefix: `TL`},
{name: `wotnot`, country: ``, mbid: ``, prefix: `WN`},
{name: `wrong planet`, country: `GB`, mbid: ``, prefix: `WPM`},
{name: `x-it music`, country: ``, mbid: ``, prefix: `XIT`},
{name: `xmg`, country: ``, mbid: ``, prefix: ``},
{name: `x-ray dog`, country: ``, mbid: `8edd417e-2738-44a7-a4b8-a5e5cfce43ce`, prefix: `XRCD`},
{name: `x-series`, country: `GB`, mbid: ``, prefix: `XCD`},
{name: `xtortion audio`, country: ``, mbid: `58630d73-0185-4585-aae3-ff79bd65e6a6`, prefix: `X`},
{name: `xueran chen`, country: ``, mbid: ``, prefix: ``},
{name: `zero degrees`, country: ``, mbid: ``, prefix: `ZRO`},
{name: `zest`, country: ``, mbid: ``, prefix: `ZST`},
{name: `zest music`, country: ``, mbid: ``, prefix: `ZEST`},
{name: `zik`, country: ``, mbid: ``, prefix: `ZIK`},
{name: `zone`, country: ``, mbid: `713ec76b-a02f-42e6-86d1-86c7c35b8315`, prefix: `ZONE`},
{name: `zone music`, country: ``, mbid: `713ec76b-a02f-42e6-86d1-86c7c35b8315`, prefix: `ZONE`},
{name: `zone plus`, country: ``, mbid: `c8b34ba3-9c56-4fbf-bc3c-8a7751f92fed`, prefix: `ZONE PLUS`},
{name: `zone trailers`, country: ``, mbid: ``, prefix: `ZTR`}
];
