const labelDB = {
        'Arcadia Cinematic': '',
        'Arcadia Classical Media Music': '',
        'Arcadia Cosmos': '',
        'Arcadia Cosmos Special Select': '',
        'Arcadia DeLuxe': 'b7a82c40-36b7-445a-a5c3-c4f453193ff6',
        'Arcadia Drones': '',
        'Arcadia EnVogue': '',
        'Arcadia Esovision': '',
        'Arcadia Galaxy Music Lexicon': '',
        'Arcadia Global Authentic Music': '',
        'Arcadia Hollywood': '',
        'Arcadia Jazz Line': '',
        'Arcadia Jingle Bank': '',
        'Arcadia Less-Is-More': '',
        'Arcadia Lifestyle': '',
        'Arcadia Loop Academy': '',
        'Arcadia MasterTrax': '',
        'Arcadia MaxMusic': '',
        'Arcadia Media Music': '',
        'Arcadia Minimal': '',
        'Arcadia National': '',
        'Arcadia Shorts': '',
        'Arcadia Spot Leitmotif': '',
        'Arcadia Therapy': '',
        'Arcadia Viva': ''
    };
